// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: app/trafficcontrol/command.proto

package trafficcontrol

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_app_trafficcontrol_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_app_trafficcontrol_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_app_trafficcontrol_command_proto_rawDescGZIP(), []int{0}
}

type Capabilities struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion    uint32                 `protobuf:"varint,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	CoreVersion   string                 `protobuf:"bytes,2,opt,name=core_version,json=coreVersion,proto3" json:"core_version,omitempty"`
	BootId        string                 `protobuf:"bytes,3,opt,name=boot_id,json=bootId,proto3" json:"boot_id,omitempty"`
	Capabilities  []string               `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Capabilities) Reset() {
	*x = Capabilities{}
	mi := &file_app_trafficcontrol_command_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capabilities) ProtoMessage() {}

func (x *Capabilities) ProtoReflect() protoreflect.Message {
	mi := &file_app_trafficcontrol_command_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capabilities.ProtoReflect.Descriptor instead.
func (*Capabilities) Descriptor() ([]byte, []int) {
	return file_app_trafficcontrol_command_proto_rawDescGZIP(), []int{1}
}

func (x *Capabilities) GetApiVersion() uint32 {
	if x != nil {
		return x.ApiVersion
	}
	return 0
}

func (x *Capabilities) GetCoreVersion() string {
	if x != nil {
		return x.CoreVersion
	}
	return ""
}

func (x *Capabilities) GetBootId() string {
	if x != nil {
		return x.BootId
	}
	return ""
}

func (x *Capabilities) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type DrainRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ExpectedBootId string                 `protobuf:"bytes,1,opt,name=expected_boot_id,json=expectedBootId,proto3" json:"expected_boot_id,omitempty"`
	AfterName      string                 `protobuf:"bytes,2,opt,name=after_name,json=afterName,proto3" json:"after_name,omitempty"`
	Limit          uint32                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DrainRequest) Reset() {
	*x = DrainRequest{}
	mi := &file_app_trafficcontrol_command_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrainRequest) ProtoMessage() {}

func (x *DrainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_trafficcontrol_command_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrainRequest.ProtoReflect.Descriptor instead.
func (*DrainRequest) Descriptor() ([]byte, []int) {
	return file_app_trafficcontrol_command_proto_rawDescGZIP(), []int{2}
}

func (x *DrainRequest) GetExpectedBootId() string {
	if x != nil {
		return x.ExpectedBootId
	}
	return ""
}

func (x *DrainRequest) GetAfterName() string {
	if x != nil {
		return x.AfterName
	}
	return ""
}

func (x *DrainRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type DrainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BootId        string                 `protobuf:"bytes,1,opt,name=boot_id,json=bootId,proto3" json:"boot_id,omitempty"`
	Counters      map[string]int64       `protobuf:"bytes,2,rep,name=counters,proto3" json:"counters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	NextName      string                 `protobuf:"bytes,3,opt,name=next_name,json=nextName,proto3" json:"next_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DrainResponse) Reset() {
	*x = DrainResponse{}
	mi := &file_app_trafficcontrol_command_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrainResponse) ProtoMessage() {}

func (x *DrainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_trafficcontrol_command_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrainResponse.ProtoReflect.Descriptor instead.
func (*DrainResponse) Descriptor() ([]byte, []int) {
	return file_app_trafficcontrol_command_proto_rawDescGZIP(), []int{3}
}

func (x *DrainResponse) GetBootId() string {
	if x != nil {
		return x.BootId
	}
	return ""
}

func (x *DrainResponse) GetCounters() map[string]int64 {
	if x != nil {
		return x.Counters
	}
	return nil
}

func (x *DrainResponse) GetNextName() string {
	if x != nil {
		return x.NextName
	}
	return ""
}

type Config struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_app_trafficcontrol_command_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_app_trafficcontrol_command_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_app_trafficcontrol_command_proto_rawDescGZIP(), []int{4}
}

var File_app_trafficcontrol_command_proto protoreflect.FileDescriptor

const file_app_trafficcontrol_command_proto_rawDesc = "" +
	"\n" +
	" app/trafficcontrol/command.proto\x12\x1axray.app.trafficcontrol.v1\"\a\n" +
	"\x05Empty\"\x8f\x01\n" +
	"\fCapabilities\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\rR\n" +
	"apiVersion\x12!\n" +
	"\fcore_version\x18\x02 \x01(\tR\vcoreVersion\x12\x17\n" +
	"\aboot_id\x18\x03 \x01(\tR\x06bootId\x12\"\n" +
	"\fcapabilities\x18\x04 \x03(\tR\fcapabilities\"m\n" +
	"\fDrainRequest\x12(\n" +
	"\x10expected_boot_id\x18\x01 \x01(\tR\x0eexpectedBootId\x12\x1d\n" +
	"\n" +
	"after_name\x18\x02 \x01(\tR\tafterName\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\"\xd7\x01\n" +
	"\rDrainResponse\x12\x17\n" +
	"\aboot_id\x18\x01 \x01(\tR\x06bootId\x12S\n" +
	"\bcounters\x18\x02 \x03(\v27.xray.app.trafficcontrol.v1.DrainResponse.CountersEntryR\bcounters\x12\x1b\n" +
	"\tnext_name\x18\x03 \x01(\tR\bnextName\x1a;\n" +
	"\rCountersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\b\n" +
	"\x06Config2\xd5\x01\n" +
	"\x15TrafficControlService\x12^\n" +
	"\x0fGetCapabilities\x12!.xray.app.trafficcontrol.v1.Empty\x1a(.xray.app.trafficcontrol.v1.Capabilities\x12\\\n" +
	"\x05Drain\x12(.xray.app.trafficcontrol.v1.DrainRequest\x1a).xray.app.trafficcontrol.v1.DrainResponseB.Z,github.com/xtls/xray-core/app/trafficcontrolb\x06proto3"

var (
	file_app_trafficcontrol_command_proto_rawDescOnce sync.Once
	file_app_trafficcontrol_command_proto_rawDescData []byte
)

func file_app_trafficcontrol_command_proto_rawDescGZIP() []byte {
	file_app_trafficcontrol_command_proto_rawDescOnce.Do(func() {
		file_app_trafficcontrol_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_trafficcontrol_command_proto_rawDesc), len(file_app_trafficcontrol_command_proto_rawDesc)))
	})
	return file_app_trafficcontrol_command_proto_rawDescData
}

var (
	file_app_trafficcontrol_command_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
	file_app_trafficcontrol_command_proto_goTypes  = []any{
		(*Empty)(nil),         // 0: xray.app.trafficcontrol.v1.Empty
		(*Capabilities)(nil),  // 1: xray.app.trafficcontrol.v1.Capabilities
		(*DrainRequest)(nil),  // 2: xray.app.trafficcontrol.v1.DrainRequest
		(*DrainResponse)(nil), // 3: xray.app.trafficcontrol.v1.DrainResponse
		(*Config)(nil),        // 4: xray.app.trafficcontrol.v1.Config
		nil,                   // 5: xray.app.trafficcontrol.v1.DrainResponse.CountersEntry
	}
)

var file_app_trafficcontrol_command_proto_depIdxs = []int32{
	5, // 0: xray.app.trafficcontrol.v1.DrainResponse.counters:type_name -> xray.app.trafficcontrol.v1.DrainResponse.CountersEntry
	0, // 1: xray.app.trafficcontrol.v1.TrafficControlService.GetCapabilities:input_type -> xray.app.trafficcontrol.v1.Empty
	2, // 2: xray.app.trafficcontrol.v1.TrafficControlService.Drain:input_type -> xray.app.trafficcontrol.v1.DrainRequest
	1, // 3: xray.app.trafficcontrol.v1.TrafficControlService.GetCapabilities:output_type -> xray.app.trafficcontrol.v1.Capabilities
	3, // 4: xray.app.trafficcontrol.v1.TrafficControlService.Drain:output_type -> xray.app.trafficcontrol.v1.DrainResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_app_trafficcontrol_command_proto_init() }
func file_app_trafficcontrol_command_proto_init() {
	if File_app_trafficcontrol_command_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_trafficcontrol_command_proto_rawDesc), len(file_app_trafficcontrol_command_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_trafficcontrol_command_proto_goTypes,
		DependencyIndexes: file_app_trafficcontrol_command_proto_depIdxs,
		MessageInfos:      file_app_trafficcontrol_command_proto_msgTypes,
	}.Build()
	File_app_trafficcontrol_command_proto = out.File
	file_app_trafficcontrol_command_proto_goTypes = nil
	file_app_trafficcontrol_command_proto_depIdxs = nil
}
