// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v7.36.2
// source: app/trafficcontrol/command.proto

package trafficcontrol

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TrafficControlService_GetCapabilities_FullMethodName = "/xray.app.trafficcontrol.v1.TrafficControlService/GetCapabilities"
	TrafficControlService_Drain_FullMethodName           = "/xray.app.trafficcontrol.v1.TrafficControlService/Drain"
)

// TrafficControlServiceClient is the client API for TrafficControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TrafficControlServiceClient interface {
	GetCapabilities(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Capabilities, error)
	Drain(ctx context.Context, in *DrainRequest, opts ...grpc.CallOption) (*DrainResponse, error)
}

type trafficControlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTrafficControlServiceClient(cc grpc.ClientConnInterface) TrafficControlServiceClient {
	return &trafficControlServiceClient{cc}
}

func (c *trafficControlServiceClient) GetCapabilities(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Capabilities, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Capabilities)
	err := c.cc.Invoke(ctx, TrafficControlService_GetCapabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trafficControlServiceClient) Drain(ctx context.Context, in *DrainRequest, opts ...grpc.CallOption) (*DrainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DrainResponse)
	err := c.cc.Invoke(ctx, TrafficControlService_Drain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TrafficControlServiceServer is the server API for TrafficControlService service.
// All implementations must embed UnimplementedTrafficControlServiceServer
// for forward compatibility.
type TrafficControlServiceServer interface {
	GetCapabilities(context.Context, *Empty) (*Capabilities, error)
	Drain(context.Context, *DrainRequest) (*DrainResponse, error)
	mustEmbedUnimplementedTrafficControlServiceServer()
}

// UnimplementedTrafficControlServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTrafficControlServiceServer struct{}

func (UnimplementedTrafficControlServiceServer) GetCapabilities(context.Context, *Empty) (*Capabilities, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCapabilities not implemented")
}

func (UnimplementedTrafficControlServiceServer) Drain(context.Context, *DrainRequest) (*DrainResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Drain not implemented")
}

func (UnimplementedTrafficControlServiceServer) mustEmbedUnimplementedTrafficControlServiceServer() {}

func (UnimplementedTrafficControlServiceServer) testEmbeddedByValue() {}

// UnsafeTrafficControlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrafficControlServiceServer will
// result in compilation errors.
type UnsafeTrafficControlServiceServer interface {
	mustEmbedUnimplementedTrafficControlServiceServer()
}

func RegisterTrafficControlServiceServer(s grpc.ServiceRegistrar, srv TrafficControlServiceServer) {
	// If the following call panics, it indicates UnimplementedTrafficControlServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TrafficControlService_ServiceDesc, srv)
}

func _TrafficControlService_GetCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrafficControlServiceServer).GetCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrafficControlService_GetCapabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrafficControlServiceServer).GetCapabilities(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrafficControlService_Drain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DrainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrafficControlServiceServer).Drain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrafficControlService_Drain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrafficControlServiceServer).Drain(ctx, req.(*DrainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TrafficControlService_ServiceDesc is the grpc.ServiceDesc for TrafficControlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TrafficControlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xray.app.trafficcontrol.v1.TrafficControlService",
	HandlerType: (*TrafficControlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCapabilities",
			Handler:    _TrafficControlService_GetCapabilities_Handler,
		},
		{
			MethodName: "Drain",
			Handler:    _TrafficControlService_Drain_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/trafficcontrol/command.proto",
}
