syntax = "proto3";

package xray.proxy.mieru;
option go_package = "github.com/xtls/xray-core/proxy/mieru";

import "common/net/address.proto";
import "common/protocol/user.proto";

message Account {
  string username = 1;
  string password = 2;
}

message ServerConfig {
  repeated xray.common.protocol.User users = 1;
  string transport = 2;
  uint32 mtu = 3;
  bool user_hint_required = 4;
  uint32 max_connections = 5;
  uint32 handshake_timeout_seconds = 6;
}

message ClientConfig {
  xray.common.net.IPOrDomain address = 1;
  uint32 port = 2;
  string username = 3;
  string password = 4;
  string transport = 5;
  string multiplexing = 6;
  uint32 mtu = 7;
}
