// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: app/clientpolicy/config.proto

package clientpolicy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PolicyConfig struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	ClientId               string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Version                uint64                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Enabled                bool                   `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	MultiplierMicros       uint64                 `protobuf:"varint,4,opt,name=multiplier_micros,json=multiplierMicros,proto3" json:"multiplier_micros,omitempty"`
	QuotaBytes             uint64                 `protobuf:"varint,5,opt,name=quota_bytes,json=quotaBytes,proto3" json:"quota_bytes,omitempty"`
	UploadBytesPerSecond   uint64                 `protobuf:"varint,6,opt,name=upload_bytes_per_second,json=uploadBytesPerSecond,proto3" json:"upload_bytes_per_second,omitempty"`
	DownloadBytesPerSecond uint64                 `protobuf:"varint,7,opt,name=download_bytes_per_second,json=downloadBytesPerSecond,proto3" json:"download_bytes_per_second,omitempty"`
	BurstBytes             uint64                 `protobuf:"varint,8,opt,name=burst_bytes,json=burstBytes,proto3" json:"burst_bytes,omitempty"`
	ExpiresAt              int64                  `protobuf:"varint,9,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PolicyConfig) Reset() {
	*x = PolicyConfig{}
	mi := &file_app_clientpolicy_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyConfig) ProtoMessage() {}

func (x *PolicyConfig) ProtoReflect() protoreflect.Message {
	mi := &file_app_clientpolicy_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyConfig.ProtoReflect.Descriptor instead.
func (*PolicyConfig) Descriptor() ([]byte, []int) {
	return file_app_clientpolicy_config_proto_rawDescGZIP(), []int{0}
}

func (x *PolicyConfig) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *PolicyConfig) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *PolicyConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *PolicyConfig) GetMultiplierMicros() uint64 {
	if x != nil {
		return x.MultiplierMicros
	}
	return 0
}

func (x *PolicyConfig) GetQuotaBytes() uint64 {
	if x != nil {
		return x.QuotaBytes
	}
	return 0
}

func (x *PolicyConfig) GetUploadBytesPerSecond() uint64 {
	if x != nil {
		return x.UploadBytesPerSecond
	}
	return 0
}

func (x *PolicyConfig) GetDownloadBytesPerSecond() uint64 {
	if x != nil {
		return x.DownloadBytesPerSecond
	}
	return 0
}

func (x *PolicyConfig) GetBurstBytes() uint64 {
	if x != nil {
		return x.BurstBytes
	}
	return 0
}

func (x *PolicyConfig) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type Config struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Policies      []*PolicyConfig        `protobuf:"bytes,1,rep,name=policies,proto3" json:"policies,omitempty"`
	StateFile     string                 `protobuf:"bytes,2,opt,name=state_file,json=stateFile,proto3" json:"state_file,omitempty"`
	InstanceId    string                 `protobuf:"bytes,3,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_app_clientpolicy_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_app_clientpolicy_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_app_clientpolicy_config_proto_rawDescGZIP(), []int{1}
}

func (x *Config) GetPolicies() []*PolicyConfig {
	if x != nil {
		return x.Policies
	}
	return nil
}

func (x *Config) GetStateFile() string {
	if x != nil {
		return x.StateFile
	}
	return ""
}

func (x *Config) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

var File_app_clientpolicy_config_proto protoreflect.FileDescriptor

const file_app_clientpolicy_config_proto_rawDesc = "" +
	"\n" +
	"\x1dapp/clientpolicy/config.proto\x12\x15xray.app.clientpolicy\"\xdf\x02\n" +
	"\fPolicyConfig\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x04R\aversion\x12\x18\n" +
	"\aenabled\x18\x03 \x01(\bR\aenabled\x12+\n" +
	"\x11multiplier_micros\x18\x04 \x01(\x04R\x10multiplierMicros\x12\x1f\n" +
	"\vquota_bytes\x18\x05 \x01(\x04R\n" +
	"quotaBytes\x125\n" +
	"\x17upload_bytes_per_second\x18\x06 \x01(\x04R\x14uploadBytesPerSecond\x129\n" +
	"\x19download_bytes_per_second\x18\a \x01(\x04R\x16downloadBytesPerSecond\x12\x1f\n" +
	"\vburst_bytes\x18\b \x01(\x04R\n" +
	"burstBytes\x12\x1d\n" +
	"\n" +
	"expires_at\x18\t \x01(\x03R\texpiresAt\"\x89\x01\n" +
	"\x06Config\x12?\n" +
	"\bpolicies\x18\x01 \x03(\v2#.xray.app.clientpolicy.PolicyConfigR\bpolicies\x12\x1d\n" +
	"\n" +
	"state_file\x18\x02 \x01(\tR\tstateFile\x12\x1f\n" +
	"\vinstance_id\x18\x03 \x01(\tR\n" +
	"instanceIdB,Z*github.com/xtls/xray-core/app/clientpolicyb\x06proto3"

var (
	file_app_clientpolicy_config_proto_rawDescOnce sync.Once
	file_app_clientpolicy_config_proto_rawDescData []byte
)

func file_app_clientpolicy_config_proto_rawDescGZIP() []byte {
	file_app_clientpolicy_config_proto_rawDescOnce.Do(func() {
		file_app_clientpolicy_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_clientpolicy_config_proto_rawDesc), len(file_app_clientpolicy_config_proto_rawDesc)))
	})
	return file_app_clientpolicy_config_proto_rawDescData
}

var file_app_clientpolicy_config_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_app_clientpolicy_config_proto_goTypes = []any{
	(*PolicyConfig)(nil), // 0: xray.app.clientpolicy.PolicyConfig
	(*Config)(nil),       // 1: xray.app.clientpolicy.Config
}
var file_app_clientpolicy_config_proto_depIdxs = []int32{
	0, // 0: xray.app.clientpolicy.Config.policies:type_name -> xray.app.clientpolicy.PolicyConfig
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_app_clientpolicy_config_proto_init() }
func file_app_clientpolicy_config_proto_init() {
	if File_app_clientpolicy_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_clientpolicy_config_proto_rawDesc), len(file_app_clientpolicy_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_app_clientpolicy_config_proto_goTypes,
		DependencyIndexes: file_app_clientpolicy_config_proto_depIdxs,
		MessageInfos:      file_app_clientpolicy_config_proto_msgTypes,
	}.Build()
	File_app_clientpolicy_config_proto = out.File
	file_app_clientpolicy_config_proto_goTypes = nil
	file_app_clientpolicy_config_proto_depIdxs = nil
}
