// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: proxy/ssh/config.proto

package ssh

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protocol "github.com/xtls/xray-core/common/protocol"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Account struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	PublicKeys    []string               `protobuf:"bytes,2,rep,name=public_keys,json=publicKeys,proto3" json:"public_keys,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_proxy_ssh_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_ssh_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_proxy_ssh_config_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Account) GetPublicKeys() []string {
	if x != nil {
		return x.PublicKeys
	}
	return nil
}

func (x *Account) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type ServerConfig struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	HostKeyFile               string                 `protobuf:"bytes,1,opt,name=host_key_file,json=hostKeyFile,proto3" json:"host_key_file,omitempty"`
	Users                     []*protocol.User       `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	AllowPassword             bool                   `protobuf:"varint,3,opt,name=allow_password,json=allowPassword,proto3" json:"allow_password,omitempty"`
	HandshakeTimeoutSeconds   uint32                 `protobuf:"varint,4,opt,name=handshake_timeout_seconds,json=handshakeTimeoutSeconds,proto3" json:"handshake_timeout_seconds,omitempty"`
	IdleTimeoutSeconds        uint32                 `protobuf:"varint,5,opt,name=idle_timeout_seconds,json=idleTimeoutSeconds,proto3" json:"idle_timeout_seconds,omitempty"`
	ChannelOpenTimeoutSeconds uint32                 `protobuf:"varint,6,opt,name=channel_open_timeout_seconds,json=channelOpenTimeoutSeconds,proto3" json:"channel_open_timeout_seconds,omitempty"`
	MaxAuthTries              uint32                 `protobuf:"varint,7,opt,name=max_auth_tries,json=maxAuthTries,proto3" json:"max_auth_tries,omitempty"`
	MaxConnections            uint32                 `protobuf:"varint,8,opt,name=max_connections,json=maxConnections,proto3" json:"max_connections,omitempty"`
	MaxConnectionsPerUser     uint32                 `protobuf:"varint,9,opt,name=max_connections_per_user,json=maxConnectionsPerUser,proto3" json:"max_connections_per_user,omitempty"`
	MaxChannelsPerConnection  uint32                 `protobuf:"varint,10,opt,name=max_channels_per_connection,json=maxChannelsPerConnection,proto3" json:"max_channels_per_connection,omitempty"`
	MaxChannels               uint32                 `protobuf:"varint,11,opt,name=max_channels,json=maxChannels,proto3" json:"max_channels,omitempty"`
	Reverse                   *ReverseConfig         `protobuf:"bytes,12,opt,name=reverse,proto3" json:"reverse,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ServerConfig) Reset() {
	*x = ServerConfig{}
	mi := &file_proxy_ssh_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerConfig) ProtoMessage() {}

func (x *ServerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_ssh_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerConfig.ProtoReflect.Descriptor instead.
func (*ServerConfig) Descriptor() ([]byte, []int) {
	return file_proxy_ssh_config_proto_rawDescGZIP(), []int{1}
}

func (x *ServerConfig) GetHostKeyFile() string {
	if x != nil {
		return x.HostKeyFile
	}
	return ""
}

func (x *ServerConfig) GetUsers() []*protocol.User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ServerConfig) GetAllowPassword() bool {
	if x != nil {
		return x.AllowPassword
	}
	return false
}

func (x *ServerConfig) GetHandshakeTimeoutSeconds() uint32 {
	if x != nil {
		return x.HandshakeTimeoutSeconds
	}
	return 0
}

func (x *ServerConfig) GetIdleTimeoutSeconds() uint32 {
	if x != nil {
		return x.IdleTimeoutSeconds
	}
	return 0
}

func (x *ServerConfig) GetChannelOpenTimeoutSeconds() uint32 {
	if x != nil {
		return x.ChannelOpenTimeoutSeconds
	}
	return 0
}

func (x *ServerConfig) GetMaxAuthTries() uint32 {
	if x != nil {
		return x.MaxAuthTries
	}
	return 0
}

func (x *ServerConfig) GetMaxConnections() uint32 {
	if x != nil {
		return x.MaxConnections
	}
	return 0
}

func (x *ServerConfig) GetMaxConnectionsPerUser() uint32 {
	if x != nil {
		return x.MaxConnectionsPerUser
	}
	return 0
}

func (x *ServerConfig) GetMaxChannelsPerConnection() uint32 {
	if x != nil {
		return x.MaxChannelsPerConnection
	}
	return 0
}

func (x *ServerConfig) GetMaxChannels() uint32 {
	if x != nil {
		return x.MaxChannels
	}
	return 0
}

func (x *ServerConfig) GetReverse() *ReverseConfig {
	if x != nil {
		return x.Reverse
	}
	return nil
}

type ReverseConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	BindAddresses []string               `protobuf:"bytes,2,rep,name=bind_addresses,json=bindAddresses,proto3" json:"bind_addresses,omitempty"`
	PortFrom      uint32                 `protobuf:"varint,3,opt,name=port_from,json=portFrom,proto3" json:"port_from,omitempty"`
	PortTo        uint32                 `protobuf:"varint,4,opt,name=port_to,json=portTo,proto3" json:"port_to,omitempty"`
	SourceCidrs   []string               `protobuf:"bytes,5,rep,name=source_cidrs,json=sourceCidrs,proto3" json:"source_cidrs,omitempty"`
	MaxListeners  uint32                 `protobuf:"varint,6,opt,name=max_listeners,json=maxListeners,proto3" json:"max_listeners,omitempty"`
	AllowPortZero bool                   `protobuf:"varint,7,opt,name=allow_port_zero,json=allowPortZero,proto3" json:"allow_port_zero,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReverseConfig) Reset() {
	*x = ReverseConfig{}
	mi := &file_proxy_ssh_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReverseConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReverseConfig) ProtoMessage() {}

func (x *ReverseConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_ssh_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReverseConfig.ProtoReflect.Descriptor instead.
func (*ReverseConfig) Descriptor() ([]byte, []int) {
	return file_proxy_ssh_config_proto_rawDescGZIP(), []int{2}
}

func (x *ReverseConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ReverseConfig) GetBindAddresses() []string {
	if x != nil {
		return x.BindAddresses
	}
	return nil
}

func (x *ReverseConfig) GetPortFrom() uint32 {
	if x != nil {
		return x.PortFrom
	}
	return 0
}

func (x *ReverseConfig) GetPortTo() uint32 {
	if x != nil {
		return x.PortTo
	}
	return 0
}

func (x *ReverseConfig) GetSourceCidrs() []string {
	if x != nil {
		return x.SourceCidrs
	}
	return nil
}

func (x *ReverseConfig) GetMaxListeners() uint32 {
	if x != nil {
		return x.MaxListeners
	}
	return 0
}

func (x *ReverseConfig) GetAllowPortZero() bool {
	if x != nil {
		return x.AllowPortZero
	}
	return false
}

type ClientConfig struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Address                 string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Port                    uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Username                string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	PrivateKeyFile          string                 `protobuf:"bytes,4,opt,name=private_key_file,json=privateKeyFile,proto3" json:"private_key_file,omitempty"`
	Password                string                 `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	HostKey                 string                 `protobuf:"bytes,6,opt,name=host_key,json=hostKey,proto3" json:"host_key,omitempty"`
	HandshakeTimeoutSeconds uint32                 `protobuf:"varint,7,opt,name=handshake_timeout_seconds,json=handshakeTimeoutSeconds,proto3" json:"handshake_timeout_seconds,omitempty"`
	IdleTimeoutSeconds      uint32                 `protobuf:"varint,8,opt,name=idle_timeout_seconds,json=idleTimeoutSeconds,proto3" json:"idle_timeout_seconds,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ClientConfig) Reset() {
	*x = ClientConfig{}
	mi := &file_proxy_ssh_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientConfig) ProtoMessage() {}

func (x *ClientConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_ssh_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientConfig.ProtoReflect.Descriptor instead.
func (*ClientConfig) Descriptor() ([]byte, []int) {
	return file_proxy_ssh_config_proto_rawDescGZIP(), []int{3}
}

func (x *ClientConfig) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ClientConfig) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ClientConfig) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ClientConfig) GetPrivateKeyFile() string {
	if x != nil {
		return x.PrivateKeyFile
	}
	return ""
}

func (x *ClientConfig) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ClientConfig) GetHostKey() string {
	if x != nil {
		return x.HostKey
	}
	return ""
}

func (x *ClientConfig) GetHandshakeTimeoutSeconds() uint32 {
	if x != nil {
		return x.HandshakeTimeoutSeconds
	}
	return 0
}

func (x *ClientConfig) GetIdleTimeoutSeconds() uint32 {
	if x != nil {
		return x.IdleTimeoutSeconds
	}
	return 0
}

var File_proxy_ssh_config_proto protoreflect.FileDescriptor

const file_proxy_ssh_config_proto_rawDesc = "" +
	"\n" +
	"\x16proxy/ssh/config.proto\x12\x0exray.proxy.ssh\x1a\x1acommon/protocol/user.proto\"b\n" +
	"\aAccount\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1f\n" +
	"\vpublic_keys\x18\x02 \x03(\tR\n" +
	"publicKeys\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"\xdd\x04\n" +
	"\fServerConfig\x12\"\n" +
	"\rhost_key_file\x18\x01 \x01(\tR\vhostKeyFile\x120\n" +
	"\x05users\x18\x02 \x03(\v2\x1a.xray.common.protocol.UserR\x05users\x12%\n" +
	"\x0eallow_password\x18\x03 \x01(\bR\rallowPassword\x12:\n" +
	"\x19handshake_timeout_seconds\x18\x04 \x01(\rR\x17handshakeTimeoutSeconds\x120\n" +
	"\x14idle_timeout_seconds\x18\x05 \x01(\rR\x12idleTimeoutSeconds\x12?\n" +
	"\x1cchannel_open_timeout_seconds\x18\x06 \x01(\rR\x19channelOpenTimeoutSeconds\x12$\n" +
	"\x0emax_auth_tries\x18\a \x01(\rR\fmaxAuthTries\x12'\n" +
	"\x0fmax_connections\x18\b \x01(\rR\x0emaxConnections\x127\n" +
	"\x18max_connections_per_user\x18\t \x01(\rR\x15maxConnectionsPerUser\x12=\n" +
	"\x1bmax_channels_per_connection\x18\n" +
	" \x01(\rR\x18maxChannelsPerConnection\x12!\n" +
	"\fmax_channels\x18\v \x01(\rR\vmaxChannels\x127\n" +
	"\areverse\x18\f \x01(\v2\x1d.xray.proxy.ssh.ReverseConfigR\areverse\"\xf6\x01\n" +
	"\rReverseConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12%\n" +
	"\x0ebind_addresses\x18\x02 \x03(\tR\rbindAddresses\x12\x1b\n" +
	"\tport_from\x18\x03 \x01(\rR\bportFrom\x12\x17\n" +
	"\aport_to\x18\x04 \x01(\rR\x06portTo\x12!\n" +
	"\fsource_cidrs\x18\x05 \x03(\tR\vsourceCidrs\x12#\n" +
	"\rmax_listeners\x18\x06 \x01(\rR\fmaxListeners\x12&\n" +
	"\x0fallow_port_zero\x18\a \x01(\bR\rallowPortZero\"\xa7\x02\n" +
	"\fClientConfig\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12(\n" +
	"\x10private_key_file\x18\x04 \x01(\tR\x0eprivateKeyFile\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\x12\x19\n" +
	"\bhost_key\x18\x06 \x01(\tR\ahostKey\x12:\n" +
	"\x19handshake_timeout_seconds\x18\a \x01(\rR\x17handshakeTimeoutSeconds\x120\n" +
	"\x14idle_timeout_seconds\x18\b \x01(\rR\x12idleTimeoutSecondsB%Z#github.com/xtls/xray-core/proxy/sshb\x06proto3"

var (
	file_proxy_ssh_config_proto_rawDescOnce sync.Once
	file_proxy_ssh_config_proto_rawDescData []byte
)

func file_proxy_ssh_config_proto_rawDescGZIP() []byte {
	file_proxy_ssh_config_proto_rawDescOnce.Do(func() {
		file_proxy_ssh_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proxy_ssh_config_proto_rawDesc), len(file_proxy_ssh_config_proto_rawDesc)))
	})
	return file_proxy_ssh_config_proto_rawDescData
}

var file_proxy_ssh_config_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proxy_ssh_config_proto_goTypes = []any{
	(*Account)(nil),       // 0: xray.proxy.ssh.Account
	(*ServerConfig)(nil),  // 1: xray.proxy.ssh.ServerConfig
	(*ReverseConfig)(nil), // 2: xray.proxy.ssh.ReverseConfig
	(*ClientConfig)(nil),  // 3: xray.proxy.ssh.ClientConfig
	(*protocol.User)(nil), // 4: xray.common.protocol.User
}
var file_proxy_ssh_config_proto_depIdxs = []int32{
	4, // 0: xray.proxy.ssh.ServerConfig.users:type_name -> xray.common.protocol.User
	2, // 1: xray.proxy.ssh.ServerConfig.reverse:type_name -> xray.proxy.ssh.ReverseConfig
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proxy_ssh_config_proto_init() }
func file_proxy_ssh_config_proto_init() {
	if File_proxy_ssh_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proxy_ssh_config_proto_rawDesc), len(file_proxy_ssh_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proxy_ssh_config_proto_goTypes,
		DependencyIndexes: file_proxy_ssh_config_proto_depIdxs,
		MessageInfos:      file_proxy_ssh_config_proto_msgTypes,
	}.Build()
	File_proxy_ssh_config_proto = out.File
	file_proxy_ssh_config_proto_goTypes = nil
	file_proxy_ssh_config_proto_depIdxs = nil
}
