import { describe, expect, it, vi } from 'vitest';
import { act, fireEvent, screen, waitFor } from '@testing-library/react';
import ClientFormModal from '@/pages/clients/ClientFormModal';
import InboundFormModal from '@/pages/inbounds/form/InboundFormModal';
import OutboundFormModal from '@/pages/xray/outbounds/OutboundFormModal';
import { DBInbound } from '@/models/dbinbound';
import type { InboundOption } from '@/schemas/client';
import { HttpUtil } from '@/utils';
import { renderWithProviders, fieldLabels } from './test-utils';

const KEY =
  'ssh-ed25519 ' +
  btoa(
    String.fromCharCode(0, 0, 0, 11) +
      'ssh-ed25519' +
      String.fromCharCode(0, 0, 0, 32) +
      'k'.repeat(32),
  );
const listener = {
  id: 9,
  protocol: 'ssh',
  port: 2222,
  enable: true,
  tag: 'ssh-native',
  sshAllowPassword: true,
  sshHostPublicKey: KEY,
  sshHostFingerprint: 'SHA256:business-trust',
} as InboundOption;
function input(label: string): HTMLInputElement | HTMLTextAreaElement {
  const field = Array.from(document.querySelectorAll('.ant-form-item')).find(
    (el) => el.querySelector('.ant-form-item-label label')?.textContent?.trim() === label,
  );
  const control = field?.querySelector<HTMLInputElement | HTMLTextAreaElement>('input,textarea');
  if (!control) throw new Error(`Missing SSH field: ${label}`);
  return control;
}
function credentials() {
  fireEvent.click(
    Array.from(document.querySelectorAll('.ant-tabs-tab')).find(
      (el) => el.textContent?.trim() === 'Credentials',
    )!,
  );
}
function attachSSH() {
  const field = Array.from(document.querySelectorAll('.ant-form-item')).find(
    (el) =>
      el.querySelector('.ant-form-item-label label')?.textContent?.trim() === 'Attached inbounds',
  )!;
  const select = field.querySelector('.ant-select')!;
  fireEvent.mouseDown(select.querySelector('.ant-select-selector') ?? select);
  const option = Array.from(document.querySelectorAll('.ant-select-item-option')).find((el) =>
    el.textContent?.includes('ssh-native'),
  )!;
  expect(option).toBeTruthy();
  fireEvent.click(option);
}

describe('native SSH existing public forms', () => {
  it('renames and attaches an account without changing independent SSH authentication', async () => {
    const save = vi.fn().mockResolvedValue({ success: true });
    renderWithProviders(
      <ClientFormModal
        open
        mode="edit"
        client={{
          email: 'label',
          enable: true,
          sshUsername: 'native-user',
          sshAuthorizedKeys: KEY,
          sshPassword: 'native-secret',
          password: 'other',
          mieruUsername: 'mieru-user',
        }}
        inbounds={[listener]}
        attachedIds={[]}
        save={save}
        onOpenChange={() => {}}
      />,
    );
    attachSSH();
    credentials();
    await waitFor(() => expect(input('SSH username').value).toBe('native-user'));
    expect(input('SSH authorized public keys').value).toBe(KEY);
    fireEvent.change(input('Email'), { target: { value: 'renamed' } });
    fireEvent.click(await screen.findByRole('button', { name: /save/i }));
    await waitFor(() => expect(save).toHaveBeenCalledTimes(1));
    expect(save.mock.calls[0][0]).toMatchObject({
      email: 'renamed',
      sshUsername: 'native-user',
      sshAuthorizedKeys: KEY,
      sshPassword: 'native-secret',
      password: 'other',
      mieruUsername: 'mieru-user',
    });
    expect(save.mock.calls[0][1]).toMatchObject({ attach: [9], detach: [], email: 'label' });
  });
  it('creates a public-key account with a username generated by the server', async () => {
    const save = vi.fn().mockResolvedValue({ success: true });
    renderWithProviders(
      <ClientFormModal
        open
        mode="add"
        client={null}
        inbounds={[listener]}
        attachedIds={[]}
        save={save}
        onOpenChange={() => {}}
      />,
    );
    attachSSH();
    credentials();
    fireEvent.change(input('Email'), { target: { value: 'new-ssh' } });
    fireEvent.change(input('SSH authorized public keys'), { target: { value: KEY } });
    fireEvent.click(await screen.findByRole('button', { name: /create/i }));
    await waitFor(() => expect(save).toHaveBeenCalledTimes(1));
    expect(save.mock.calls[0][0]).toMatchObject({
      inboundIds: [9],
      client: { email: 'new-ssh', sshUsername: '', sshAuthorizedKeys: KEY, sshPassword: '' },
    });
  });
  it('prevents clearing the last authentication method on a key-only listener', async () => {
    const save = vi.fn();
    renderWithProviders(
      <ClientFormModal
        open
        mode="edit"
        client={{
          email: 'label',
          enable: true,
          sshUsername: 'native-user',
          sshAuthorizedKeys: KEY,
          sshPassword: 'stored-but-disallowed',
        }}
        inbounds={[{ ...listener, sshAllowPassword: false }]}
        attachedIds={[9]}
        save={save}
        onOpenChange={() => {}}
      />,
    );
    credentials();
    fireEvent.click(await screen.findByRole('switch', { name: 'Clear stored SSH public keys' }));
    fireEvent.click(await screen.findByRole('button', { name: /save/i }));
    await screen.findByText(
      'Provide SSH public keys, or a password accepted by every selected SSH listener.',
    );
    expect(save).not.toHaveBeenCalled();
  });
  it('explicitly clears only the SSH password while preserving public-key authentication', async () => {
    const save = vi.fn().mockResolvedValue({ success: true });
    renderWithProviders(
      <ClientFormModal
        open
        mode="edit"
        client={{
          email: 'label',
          enable: true,
          sshUsername: 'native-user',
          sshAuthorizedKeys: KEY,
          sshPassword: 'native-secret',
        }}
        inbounds={[listener]}
        attachedIds={[9]}
        save={save}
        onOpenChange={() => {}}
      />,
    );
    credentials();
    fireEvent.click(await screen.findByRole('switch', { name: 'Clear stored SSH password' }));
    fireEvent.click(await screen.findByRole('button', { name: /save/i }));
    await waitFor(() => expect(save).toHaveBeenCalledTimes(1));
    expect(save.mock.calls[0][0]).toMatchObject({
      sshPassword: '',
      clearSshPassword: true,
      sshAuthorizedKeys: KEY,
      clearSshAuthorizedKeys: false,
    });
    expect(screen.getByText('SHA256:business-trust')).toBeTruthy();
  });
  it('reopens and saves bounded listener and reverse controls', async () => {
    const settings = {
      clients: [],
      allowPassword: false,
      maxConnections: 32,
      reverse: {
        enabled: true,
        bindAddresses: ['127.0.0.1'],
        portFrom: 22000,
        portTo: 22010,
        sourceCIDRs: ['127.0.0.0/8'],
        maxListeners: 2,
        allowPortZero: false,
      },
    };
    const inbound = new DBInbound({
      id: 9,
      protocol: 'ssh',
      port: 2222,
      enable: true,
      settings,
      streamSettings: {},
      sniffing: {},
    });
    const post = vi
      .spyOn(HttpUtil, 'post')
      .mockResolvedValue({ success: true, msg: '', obj: inbound } as never);
    renderWithProviders(
      <InboundFormModal
        open
        mode="edit"
        dbInbound={inbound}
        dbInbounds={[inbound]}
        availableNodes={[]}
        onClose={() => {}}
        onSaved={() => {}}
      />,
    );
    await waitFor(() => expect(fieldLabels()).toContain('Allow password authentication'));
    expect(fieldLabels()).toContain('Reverse bind addresses');
    expect(fieldLabels()).not.toContain('Security');
    await act(async () =>
      fireEvent.click(document.querySelector('.ant-modal-footer .ant-btn-primary')!),
    );
    await waitFor(() => expect(post).toHaveBeenCalled());
    expect(
      JSON.parse((post.mock.calls.at(-1)![1] as Record<string, unknown>).settings as string),
    ).toMatchObject(settings);
  });
  it('saves an outbound with an actual pinned host public key and independent password', async () => {
    const settings = {
      address: 'example.test',
      port: 2222,
      username: 'native-user',
      password: 'secret',
      hostKey: KEY,
    };
    const confirm = vi.fn();
    renderWithProviders(
      <OutboundFormModal
        open
        outbound={{ protocol: 'ssh', tag: 'native', settings }}
        existingTags={[]}
        onClose={() => {}}
        onConfirm={confirm}
      />,
    );
    await waitFor(() => expect(input('Pinned SSH host public key').value).toBe(KEY));
    expect(fieldLabels()).not.toContain('Security');
    await act(async () =>
      fireEvent.click(document.querySelector('.ant-modal-footer .ant-btn-primary')!),
    );
    await waitFor(() => expect(confirm).toHaveBeenCalledTimes(1));
    expect(confirm.mock.calls[0][0]).toMatchObject({ protocol: 'ssh', settings });
    expect(confirm.mock.calls[0][0]).not.toHaveProperty('mux');
  });
});
