// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: app/clientpolicy/command/command.proto

package command

import (
	clientpolicy "github.com/xtls/xray-core/app/clientpolicy"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_app_clientpolicy_command_command_proto_rawDescGZIP(), []int{0}
}

type ClientRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ClientId              string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ExpectedPolicyVersion uint64                 `protobuf:"varint,2,opt,name=expected_policy_version,json=expectedPolicyVersion,proto3" json:"expected_policy_version,omitempty"`
	InboundTag            string                 `protobuf:"bytes,3,opt,name=inbound_tag,json=inboundTag,proto3" json:"inbound_tag,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ClientRequest) Reset() {
	*x = ClientRequest{}
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientRequest) ProtoMessage() {}

func (x *ClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientRequest.ProtoReflect.Descriptor instead.
func (*ClientRequest) Descriptor() ([]byte, []int) {
	return file_app_clientpolicy_command_command_proto_rawDescGZIP(), []int{1}
}

func (x *ClientRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ClientRequest) GetExpectedPolicyVersion() uint64 {
	if x != nil {
		return x.ExpectedPolicyVersion
	}
	return 0
}

func (x *ClientRequest) GetInboundTag() string {
	if x != nil {
		return x.InboundTag
	}
	return ""
}

type Capabilities struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion          uint32                 `protobuf:"varint,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	CoreVersion         string                 `protobuf:"bytes,2,opt,name=core_version,json=coreVersion,proto3" json:"core_version,omitempty"`
	InstanceId          string                 `protobuf:"bytes,3,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Epoch               uint64                 `protobuf:"varint,4,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Capabilities        []string               `protobuf:"bytes,5,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	ReservationRawBytes uint64                 `protobuf:"varint,6,opt,name=reservation_raw_bytes,json=reservationRawBytes,proto3" json:"reservation_raw_bytes,omitempty"`
	BootId              string                 `protobuf:"bytes,7,opt,name=boot_id,json=bootId,proto3" json:"boot_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Capabilities) Reset() {
	*x = Capabilities{}
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capabilities) ProtoMessage() {}

func (x *Capabilities) ProtoReflect() protoreflect.Message {
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capabilities.ProtoReflect.Descriptor instead.
func (*Capabilities) Descriptor() ([]byte, []int) {
	return file_app_clientpolicy_command_command_proto_rawDescGZIP(), []int{2}
}

func (x *Capabilities) GetApiVersion() uint32 {
	if x != nil {
		return x.ApiVersion
	}
	return 0
}

func (x *Capabilities) GetCoreVersion() string {
	if x != nil {
		return x.CoreVersion
	}
	return ""
}

func (x *Capabilities) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *Capabilities) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *Capabilities) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *Capabilities) GetReservationRawBytes() uint64 {
	if x != nil {
		return x.ReservationRawBytes
	}
	return 0
}

func (x *Capabilities) GetBootId() string {
	if x != nil {
		return x.BootId
	}
	return ""
}

type AuthorityChallengeRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ExpectedBootId string                 `protobuf:"bytes,1,opt,name=expected_boot_id,json=expectedBootId,proto3" json:"expected_boot_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AuthorityChallengeRequest) Reset() {
	*x = AuthorityChallengeRequest{}
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorityChallengeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorityChallengeRequest) ProtoMessage() {}

func (x *AuthorityChallengeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorityChallengeRequest.ProtoReflect.Descriptor instead.
func (*AuthorityChallengeRequest) Descriptor() ([]byte, []int) {
	return file_app_clientpolicy_command_command_proto_rawDescGZIP(), []int{3}
}

func (x *AuthorityChallengeRequest) GetExpectedBootId() string {
	if x != nil {
		return x.ExpectedBootId
	}
	return ""
}

type AuthorityChallenge struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	InstanceId        string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	BootId            string                 `protobuf:"bytes,2,opt,name=boot_id,json=bootId,proto3" json:"boot_id,omitempty"`
	ChallengeId       string                 `protobuf:"bytes,3,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	MaxDurationMillis uint64                 `protobuf:"varint,4,opt,name=max_duration_millis,json=maxDurationMillis,proto3" json:"max_duration_millis,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AuthorityChallenge) Reset() {
	*x = AuthorityChallenge{}
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorityChallenge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorityChallenge) ProtoMessage() {}

func (x *AuthorityChallenge) ProtoReflect() protoreflect.Message {
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorityChallenge.ProtoReflect.Descriptor instead.
func (*AuthorityChallenge) Descriptor() ([]byte, []int) {
	return file_app_clientpolicy_command_command_proto_rawDescGZIP(), []int{4}
}

func (x *AuthorityChallenge) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *AuthorityChallenge) GetBootId() string {
	if x != nil {
		return x.BootId
	}
	return ""
}

func (x *AuthorityChallenge) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

func (x *AuthorityChallenge) GetMaxDurationMillis() uint64 {
	if x != nil {
		return x.MaxDurationMillis
	}
	return 0
}

type AuthorityBinding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthorityId   string                 `protobuf:"bytes,1,opt,name=authority_id,json=authorityId,proto3" json:"authority_id,omitempty"`
	Generation    uint64                 `protobuf:"varint,2,opt,name=generation,proto3" json:"generation,omitempty"`
	NodeId        string                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorityBinding) Reset() {
	*x = AuthorityBinding{}
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorityBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorityBinding) ProtoMessage() {}

func (x *AuthorityBinding) ProtoReflect() protoreflect.Message {
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorityBinding.ProtoReflect.Descriptor instead.
func (*AuthorityBinding) Descriptor() ([]byte, []int) {
	return file_app_clientpolicy_command_command_proto_rawDescGZIP(), []int{5}
}

func (x *AuthorityBinding) GetAuthorityId() string {
	if x != nil {
		return x.AuthorityId
	}
	return ""
}

func (x *AuthorityBinding) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *AuthorityBinding) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type AuthorityShare struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Unlimited     bool                   `protobuf:"varint,1,opt,name=unlimited,proto3" json:"unlimited,omitempty"`
	Rate          uint64                 `protobuf:"varint,2,opt,name=rate,proto3" json:"rate,omitempty"`
	Burst         uint64                 `protobuf:"varint,3,opt,name=burst,proto3" json:"burst,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorityShare) Reset() {
	*x = AuthorityShare{}
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorityShare) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorityShare) ProtoMessage() {}

func (x *AuthorityShare) ProtoReflect() protoreflect.Message {
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorityShare.ProtoReflect.Descriptor instead.
func (*AuthorityShare) Descriptor() ([]byte, []int) {
	return file_app_clientpolicy_command_command_proto_rawDescGZIP(), []int{6}
}

func (x *AuthorityShare) GetUnlimited() bool {
	if x != nil {
		return x.Unlimited
	}
	return false
}

func (x *AuthorityShare) GetRate() uint64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *AuthorityShare) GetBurst() uint64 {
	if x != nil {
		return x.Burst
	}
	return 0
}

type AuthorityBindRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ExpectedBootId string                 `protobuf:"bytes,1,opt,name=expected_boot_id,json=expectedBootId,proto3" json:"expected_boot_id,omitempty"`
	Authority      *AuthorityBinding      `protobuf:"bytes,2,opt,name=authority,proto3" json:"authority,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AuthorityBindRequest) Reset() {
	*x = AuthorityBindRequest{}
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorityBindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorityBindRequest) ProtoMessage() {}

func (x *AuthorityBindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorityBindRequest.ProtoReflect.Descriptor instead.
func (*AuthorityBindRequest) Descriptor() ([]byte, []int) {
	return file_app_clientpolicy_command_command_proto_rawDescGZIP(), []int{7}
}

func (x *AuthorityBindRequest) GetExpectedBootId() string {
	if x != nil {
		return x.ExpectedBootId
	}
	return ""
}

func (x *AuthorityBindRequest) GetAuthority() *AuthorityBinding {
	if x != nil {
		return x.Authority
	}
	return nil
}

type AuthorityRequestsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ExpectedBootId string                 `protobuf:"bytes,1,opt,name=expected_boot_id,json=expectedBootId,proto3" json:"expected_boot_id,omitempty"`
	Authority      *AuthorityBinding      `protobuf:"bytes,2,opt,name=authority,proto3" json:"authority,omitempty"`
	Limit          uint32                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AuthorityRequestsRequest) Reset() {
	*x = AuthorityRequestsRequest{}
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorityRequestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorityRequestsRequest) ProtoMessage() {}

func (x *AuthorityRequestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorityRequestsRequest.ProtoReflect.Descriptor instead.
func (*AuthorityRequestsRequest) Descriptor() ([]byte, []int) {
	return file_app_clientpolicy_command_command_proto_rawDescGZIP(), []int{8}
}

func (x *AuthorityRequestsRequest) GetExpectedBootId() string {
	if x != nil {
		return x.ExpectedBootId
	}
	return ""
}

func (x *AuthorityRequestsRequest) GetAuthority() *AuthorityBinding {
	if x != nil {
		return x.Authority
	}
	return nil
}

func (x *AuthorityRequestsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type AuthorityRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RequestId       string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ClientId        string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	PolicyVersion   uint64                 `protobuf:"varint,3,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	PreviousGrantId string                 `protobuf:"bytes,4,opt,name=previous_grant_id,json=previousGrantId,proto3" json:"previous_grant_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AuthorityRequest) Reset() {
	*x = AuthorityRequest{}
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorityRequest) ProtoMessage() {}

func (x *AuthorityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorityRequest.ProtoReflect.Descriptor instead.
func (*AuthorityRequest) Descriptor() ([]byte, []int) {
	return file_app_clientpolicy_command_command_proto_rawDescGZIP(), []int{9}
}

func (x *AuthorityRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AuthorityRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *AuthorityRequest) GetPolicyVersion() uint64 {
	if x != nil {
		return x.PolicyVersion
	}
	return 0
}

func (x *AuthorityRequest) GetPreviousGrantId() string {
	if x != nil {
		return x.PreviousGrantId
	}
	return ""
}

type AuthorityRequests struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	BootId        string                 `protobuf:"bytes,2,opt,name=boot_id,json=bootId,proto3" json:"boot_id,omitempty"`
	Requests      []*AuthorityRequest    `protobuf:"bytes,3,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorityRequests) Reset() {
	*x = AuthorityRequests{}
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorityRequests) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorityRequests) ProtoMessage() {}

func (x *AuthorityRequests) ProtoReflect() protoreflect.Message {
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorityRequests.ProtoReflect.Descriptor instead.
func (*AuthorityRequests) Descriptor() ([]byte, []int) {
	return file_app_clientpolicy_command_command_proto_rawDescGZIP(), []int{10}
}

func (x *AuthorityRequests) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *AuthorityRequests) GetBootId() string {
	if x != nil {
		return x.BootId
	}
	return ""
}

func (x *AuthorityRequests) GetRequests() []*AuthorityRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type ExecutionGrant struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Authority           *AuthorityBinding      `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	InstanceId          string                 `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	BootId              string                 `protobuf:"bytes,3,opt,name=boot_id,json=bootId,proto3" json:"boot_id,omitempty"`
	ClientId            string                 `protobuf:"bytes,4,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	WindowId            string                 `protobuf:"bytes,5,opt,name=window_id,json=windowId,proto3" json:"window_id,omitempty"`
	PolicyVersion       uint64                 `protobuf:"varint,6,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	GrantId             string                 `protobuf:"bytes,7,opt,name=grant_id,json=grantId,proto3" json:"grant_id,omitempty"`
	Sequence            uint64                 `protobuf:"varint,8,opt,name=sequence,proto3" json:"sequence,omitempty"`
	ChallengeId         string                 `protobuf:"bytes,9,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	Capacity            uint64                 `protobuf:"varint,10,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Upload              *AuthorityShare        `protobuf:"bytes,11,opt,name=upload,proto3" json:"upload,omitempty"`
	Download            *AuthorityShare        `protobuf:"bytes,12,opt,name=download,proto3" json:"download,omitempty"`
	LeaseDurationMillis uint64                 `protobuf:"varint,13,opt,name=lease_duration_millis,json=leaseDurationMillis,proto3" json:"lease_duration_millis,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ExecutionGrant) Reset() {
	*x = ExecutionGrant{}
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionGrant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionGrant) ProtoMessage() {}

func (x *ExecutionGrant) ProtoReflect() protoreflect.Message {
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionGrant.ProtoReflect.Descriptor instead.
func (*ExecutionGrant) Descriptor() ([]byte, []int) {
	return file_app_clientpolicy_command_command_proto_rawDescGZIP(), []int{11}
}

func (x *ExecutionGrant) GetAuthority() *AuthorityBinding {
	if x != nil {
		return x.Authority
	}
	return nil
}

func (x *ExecutionGrant) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *ExecutionGrant) GetBootId() string {
	if x != nil {
		return x.BootId
	}
	return ""
}

func (x *ExecutionGrant) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ExecutionGrant) GetWindowId() string {
	if x != nil {
		return x.WindowId
	}
	return ""
}

func (x *ExecutionGrant) GetPolicyVersion() uint64 {
	if x != nil {
		return x.PolicyVersion
	}
	return 0
}

func (x *ExecutionGrant) GetGrantId() string {
	if x != nil {
		return x.GrantId
	}
	return ""
}

func (x *ExecutionGrant) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *ExecutionGrant) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

func (x *ExecutionGrant) GetCapacity() uint64 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *ExecutionGrant) GetUpload() *AuthorityShare {
	if x != nil {
		return x.Upload
	}
	return nil
}

func (x *ExecutionGrant) GetDownload() *AuthorityShare {
	if x != nil {
		return x.Download
	}
	return nil
}

func (x *ExecutionGrant) GetLeaseDurationMillis() uint64 {
	if x != nil {
		return x.LeaseDurationMillis
	}
	return 0
}

type AuthorityGrantRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ExpectedBootId   string                 `protobuf:"bytes,1,opt,name=expected_boot_id,json=expectedBootId,proto3" json:"expected_boot_id,omitempty"`
	ClientId         string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	GrantId          string                 `protobuf:"bytes,3,opt,name=grant_id,json=grantId,proto3" json:"grant_id,omitempty"`
	PreserveSessions bool                   `protobuf:"varint,4,opt,name=preserve_sessions,json=preserveSessions,proto3" json:"preserve_sessions,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AuthorityGrantRequest) Reset() {
	*x = AuthorityGrantRequest{}
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorityGrantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorityGrantRequest) ProtoMessage() {}

func (x *AuthorityGrantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorityGrantRequest.ProtoReflect.Descriptor instead.
func (*AuthorityGrantRequest) Descriptor() ([]byte, []int) {
	return file_app_clientpolicy_command_command_proto_rawDescGZIP(), []int{12}
}

func (x *AuthorityGrantRequest) GetExpectedBootId() string {
	if x != nil {
		return x.ExpectedBootId
	}
	return ""
}

func (x *AuthorityGrantRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *AuthorityGrantRequest) GetGrantId() string {
	if x != nil {
		return x.GrantId
	}
	return ""
}

func (x *AuthorityGrantRequest) GetPreserveSessions() bool {
	if x != nil {
		return x.PreserveSessions
	}
	return false
}

type AuthorityRenewalRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ExpectedBootId      string                 `protobuf:"bytes,1,opt,name=expected_boot_id,json=expectedBootId,proto3" json:"expected_boot_id,omitempty"`
	ClientId            string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	GrantId             string                 `protobuf:"bytes,3,opt,name=grant_id,json=grantId,proto3" json:"grant_id,omitempty"`
	ChallengeId         string                 `protobuf:"bytes,4,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	Sequence            uint64                 `protobuf:"varint,5,opt,name=sequence,proto3" json:"sequence,omitempty"`
	LeaseDurationMillis uint64                 `protobuf:"varint,6,opt,name=lease_duration_millis,json=leaseDurationMillis,proto3" json:"lease_duration_millis,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AuthorityRenewalRequest) Reset() {
	*x = AuthorityRenewalRequest{}
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorityRenewalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorityRenewalRequest) ProtoMessage() {}

func (x *AuthorityRenewalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorityRenewalRequest.ProtoReflect.Descriptor instead.
func (*AuthorityRenewalRequest) Descriptor() ([]byte, []int) {
	return file_app_clientpolicy_command_command_proto_rawDescGZIP(), []int{13}
}

func (x *AuthorityRenewalRequest) GetExpectedBootId() string {
	if x != nil {
		return x.ExpectedBootId
	}
	return ""
}

func (x *AuthorityRenewalRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *AuthorityRenewalRequest) GetGrantId() string {
	if x != nil {
		return x.GrantId
	}
	return ""
}

func (x *AuthorityRenewalRequest) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

func (x *AuthorityRenewalRequest) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *AuthorityRenewalRequest) GetLeaseDurationMillis() uint64 {
	if x != nil {
		return x.LeaseDurationMillis
	}
	return 0
}

type ExecutionGrantState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Grant         *ExecutionGrant        `protobuf:"bytes,1,opt,name=grant,proto3" json:"grant,omitempty"`
	Usage         *Usage                 `protobuf:"bytes,2,opt,name=usage,proto3" json:"usage,omitempty"`
	Sequence      uint64                 `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Sealed        bool                   `protobuf:"varint,4,opt,name=sealed,proto3" json:"sealed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionGrantState) Reset() {
	*x = ExecutionGrantState{}
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionGrantState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionGrantState) ProtoMessage() {}

func (x *ExecutionGrantState) ProtoReflect() protoreflect.Message {
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionGrantState.ProtoReflect.Descriptor instead.
func (*ExecutionGrantState) Descriptor() ([]byte, []int) {
	return file_app_clientpolicy_command_command_proto_rawDescGZIP(), []int{14}
}

func (x *ExecutionGrantState) GetGrant() *ExecutionGrant {
	if x != nil {
		return x.Grant
	}
	return nil
}

func (x *ExecutionGrantState) GetUsage() *Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *ExecutionGrantState) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *ExecutionGrantState) GetSealed() bool {
	if x != nil {
		return x.Sealed
	}
	return false
}

type Usage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RawUpload     uint64                 `protobuf:"varint,1,opt,name=raw_upload,json=rawUpload,proto3" json:"raw_upload,omitempty"`
	RawDownload   uint64                 `protobuf:"varint,2,opt,name=raw_download,json=rawDownload,proto3" json:"raw_download,omitempty"`
	BilledBytes   uint64                 `protobuf:"varint,3,opt,name=billed_bytes,json=billedBytes,proto3" json:"billed_bytes,omitempty"`
	Remainder     uint64                 `protobuf:"varint,4,opt,name=remainder,proto3" json:"remainder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Usage) Reset() {
	*x = Usage{}
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Usage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Usage) ProtoMessage() {}

func (x *Usage) ProtoReflect() protoreflect.Message {
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Usage.ProtoReflect.Descriptor instead.
func (*Usage) Descriptor() ([]byte, []int) {
	return file_app_clientpolicy_command_command_proto_rawDescGZIP(), []int{15}
}

func (x *Usage) GetRawUpload() uint64 {
	if x != nil {
		return x.RawUpload
	}
	return 0
}

func (x *Usage) GetRawDownload() uint64 {
	if x != nil {
		return x.RawDownload
	}
	return 0
}

func (x *Usage) GetBilledBytes() uint64 {
	if x != nil {
		return x.BilledBytes
	}
	return 0
}

func (x *Usage) GetRemainder() uint64 {
	if x != nil {
		return x.Remainder
	}
	return 0
}

type ClientState struct {
	state                 protoimpl.MessageState     `protogen:"open.v1"`
	Policy                *clientpolicy.PolicyConfig `protobuf:"bytes,1,opt,name=policy,proto3" json:"policy,omitempty"`
	Usage                 *Usage                     `protobuf:"bytes,2,opt,name=usage,proto3" json:"usage,omitempty"`
	UncertainBytes        uint64                     `protobuf:"varint,3,opt,name=uncertain_bytes,json=uncertainBytes,proto3" json:"uncertain_bytes,omitempty"`
	Reasons               uint32                     `protobuf:"varint,4,opt,name=reasons,proto3" json:"reasons,omitempty"`
	ActiveSessions        uint32                     `protobuf:"varint,5,opt,name=active_sessions,json=activeSessions,proto3" json:"active_sessions,omitempty"`
	FirstUsedAt           int64                      `protobuf:"varint,6,opt,name=first_used_at,json=firstUsedAt,proto3" json:"first_used_at,omitempty"`
	AuthorityGrantHistory bool                       `protobuf:"varint,7,opt,name=authority_grant_history,json=authorityGrantHistory,proto3" json:"authority_grant_history,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ClientState) Reset() {
	*x = ClientState{}
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientState) ProtoMessage() {}

func (x *ClientState) ProtoReflect() protoreflect.Message {
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientState.ProtoReflect.Descriptor instead.
func (*ClientState) Descriptor() ([]byte, []int) {
	return file_app_clientpolicy_command_command_proto_rawDescGZIP(), []int{16}
}

func (x *ClientState) GetPolicy() *clientpolicy.PolicyConfig {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *ClientState) GetUsage() *Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *ClientState) GetUncertainBytes() uint64 {
	if x != nil {
		return x.UncertainBytes
	}
	return 0
}

func (x *ClientState) GetReasons() uint32 {
	if x != nil {
		return x.Reasons
	}
	return 0
}

func (x *ClientState) GetActiveSessions() uint32 {
	if x != nil {
		return x.ActiveSessions
	}
	return 0
}

func (x *ClientState) GetFirstUsedAt() int64 {
	if x != nil {
		return x.FirstUsedAt
	}
	return 0
}

func (x *ClientState) GetAuthorityGrantHistory() bool {
	if x != nil {
		return x.AuthorityGrantHistory
	}
	return false
}

type ApplyRequest struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Policies      []*clientpolicy.PolicyConfig `protobuf:"bytes,1,rep,name=policies,proto3" json:"policies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyRequest) Reset() {
	*x = ApplyRequest{}
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyRequest) ProtoMessage() {}

func (x *ApplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyRequest.ProtoReflect.Descriptor instead.
func (*ApplyRequest) Descriptor() ([]byte, []int) {
	return file_app_clientpolicy_command_command_proto_rawDescGZIP(), []int{17}
}

func (x *ApplyRequest) GetPolicies() []*clientpolicy.PolicyConfig {
	if x != nil {
		return x.Policies
	}
	return nil
}

type InitializeRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Policy        *clientpolicy.PolicyConfig `protobuf:"bytes,1,opt,name=policy,proto3" json:"policy,omitempty"`
	Usage         *Usage                     `protobuf:"bytes,2,opt,name=usage,proto3" json:"usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitializeRequest) Reset() {
	*x = InitializeRequest{}
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeRequest) ProtoMessage() {}

func (x *InitializeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeRequest.ProtoReflect.Descriptor instead.
func (*InitializeRequest) Descriptor() ([]byte, []int) {
	return file_app_clientpolicy_command_command_proto_rawDescGZIP(), []int{18}
}

func (x *InitializeRequest) GetPolicy() *clientpolicy.PolicyConfig {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *InitializeRequest) GetUsage() *Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

type ReconcileUsageRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ExpectedBootId string                 `protobuf:"bytes,1,opt,name=expected_boot_id,json=expectedBootId,proto3" json:"expected_boot_id,omitempty"`
	ClientId       string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Usage          *Usage                 `protobuf:"bytes,3,opt,name=usage,proto3" json:"usage,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReconcileUsageRequest) Reset() {
	*x = ReconcileUsageRequest{}
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconcileUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconcileUsageRequest) ProtoMessage() {}

func (x *ReconcileUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconcileUsageRequest.ProtoReflect.Descriptor instead.
func (*ReconcileUsageRequest) Descriptor() ([]byte, []int) {
	return file_app_clientpolicy_command_command_proto_rawDescGZIP(), []int{19}
}

func (x *ReconcileUsageRequest) GetExpectedBootId() string {
	if x != nil {
		return x.ExpectedBootId
	}
	return ""
}

func (x *ReconcileUsageRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ReconcileUsageRequest) GetUsage() *Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

type Connection struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	SessionId            uint64                 `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	InboundTag           string                 `protobuf:"bytes,2,opt,name=inbound_tag,json=inboundTag,proto3" json:"inbound_tag,omitempty"`
	AuthenticatedAccount string                 `protobuf:"bytes,3,opt,name=authenticated_account,json=authenticatedAccount,proto3" json:"authenticated_account,omitempty"`
	OriginalTarget       string                 `protobuf:"bytes,4,opt,name=original_target,json=originalTarget,proto3" json:"original_target,omitempty"`
	ActualTarget         string                 `protobuf:"bytes,5,opt,name=actual_target,json=actualTarget,proto3" json:"actual_target,omitempty"`
	PolicyVersion        uint64                 `protobuf:"varint,6,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Connection) Reset() {
	*x = Connection{}
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Connection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Connection) ProtoMessage() {}

func (x *Connection) ProtoReflect() protoreflect.Message {
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Connection.ProtoReflect.Descriptor instead.
func (*Connection) Descriptor() ([]byte, []int) {
	return file_app_clientpolicy_command_command_proto_rawDescGZIP(), []int{20}
}

func (x *Connection) GetSessionId() uint64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *Connection) GetInboundTag() string {
	if x != nil {
		return x.InboundTag
	}
	return ""
}

func (x *Connection) GetAuthenticatedAccount() string {
	if x != nil {
		return x.AuthenticatedAccount
	}
	return ""
}

func (x *Connection) GetOriginalTarget() string {
	if x != nil {
		return x.OriginalTarget
	}
	return ""
}

func (x *Connection) GetActualTarget() string {
	if x != nil {
		return x.ActualTarget
	}
	return ""
}

func (x *Connection) GetPolicyVersion() uint64 {
	if x != nil {
		return x.PolicyVersion
	}
	return 0
}

type Connections struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connections   []*Connection          `protobuf:"bytes,1,rep,name=connections,proto3" json:"connections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Connections) Reset() {
	*x = Connections{}
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Connections) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Connections) ProtoMessage() {}

func (x *Connections) ProtoReflect() protoreflect.Message {
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Connections.ProtoReflect.Descriptor instead.
func (*Connections) Descriptor() ([]byte, []int) {
	return file_app_clientpolicy_command_command_proto_rawDescGZIP(), []int{21}
}

func (x *Connections) GetConnections() []*Connection {
	if x != nil {
		return x.Connections
	}
	return nil
}

type CloseResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Closed        uint32                 `protobuf:"varint,1,opt,name=closed,proto3" json:"closed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseResult) Reset() {
	*x = CloseResult{}
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseResult) ProtoMessage() {}

func (x *CloseResult) ProtoReflect() protoreflect.Message {
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseResult.ProtoReflect.Descriptor instead.
func (*CloseResult) Descriptor() ([]byte, []int) {
	return file_app_clientpolicy_command_command_proto_rawDescGZIP(), []int{22}
}

func (x *CloseResult) GetClosed() uint32 {
	if x != nil {
		return x.Closed
	}
	return 0
}

type LedgerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AfterSequence uint64                 `protobuf:"varint,1,opt,name=after_sequence,json=afterSequence,proto3" json:"after_sequence,omitempty"`
	Limit         uint32                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LedgerRequest) Reset() {
	*x = LedgerRequest{}
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedgerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerRequest) ProtoMessage() {}

func (x *LedgerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedgerRequest.ProtoReflect.Descriptor instead.
func (*LedgerRequest) Descriptor() ([]byte, []int) {
	return file_app_clientpolicy_command_command_proto_rawDescGZIP(), []int{23}
}

func (x *LedgerRequest) GetAfterSequence() uint64 {
	if x != nil {
		return x.AfterSequence
	}
	return 0
}

func (x *LedgerRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type LedgerRecord struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	InstanceId     string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Epoch          uint64                 `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Sequence       uint64                 `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	ClientId       string                 `protobuf:"bytes,4,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	PolicyVersion  uint64                 `protobuf:"varint,5,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	Usage          *Usage                 `protobuf:"bytes,6,opt,name=usage,proto3" json:"usage,omitempty"`
	UncertainBytes uint64                 `protobuf:"varint,7,opt,name=uncertain_bytes,json=uncertainBytes,proto3" json:"uncertain_bytes,omitempty"`
	ReservedBytes  uint64                 `protobuf:"varint,8,opt,name=reserved_bytes,json=reservedBytes,proto3" json:"reserved_bytes,omitempty"`
	Revoked        bool                   `protobuf:"varint,9,opt,name=revoked,proto3" json:"revoked,omitempty"`
	FirstUsedAt    int64                  `protobuf:"varint,10,opt,name=first_used_at,json=firstUsedAt,proto3" json:"first_used_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LedgerRecord) Reset() {
	*x = LedgerRecord{}
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedgerRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerRecord) ProtoMessage() {}

func (x *LedgerRecord) ProtoReflect() protoreflect.Message {
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedgerRecord.ProtoReflect.Descriptor instead.
func (*LedgerRecord) Descriptor() ([]byte, []int) {
	return file_app_clientpolicy_command_command_proto_rawDescGZIP(), []int{24}
}

func (x *LedgerRecord) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *LedgerRecord) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *LedgerRecord) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *LedgerRecord) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *LedgerRecord) GetPolicyVersion() uint64 {
	if x != nil {
		return x.PolicyVersion
	}
	return 0
}

func (x *LedgerRecord) GetUsage() *Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *LedgerRecord) GetUncertainBytes() uint64 {
	if x != nil {
		return x.UncertainBytes
	}
	return 0
}

func (x *LedgerRecord) GetReservedBytes() uint64 {
	if x != nil {
		return x.ReservedBytes
	}
	return 0
}

func (x *LedgerRecord) GetRevoked() bool {
	if x != nil {
		return x.Revoked
	}
	return false
}

func (x *LedgerRecord) GetFirstUsedAt() int64 {
	if x != nil {
		return x.FirstUsedAt
	}
	return 0
}

type LedgerPage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*LedgerRecord        `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	NextSequence  uint64                 `protobuf:"varint,2,opt,name=next_sequence,json=nextSequence,proto3" json:"next_sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LedgerPage) Reset() {
	*x = LedgerPage{}
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedgerPage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerPage) ProtoMessage() {}

func (x *LedgerPage) ProtoReflect() protoreflect.Message {
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedgerPage.ProtoReflect.Descriptor instead.
func (*LedgerPage) Descriptor() ([]byte, []int) {
	return file_app_clientpolicy_command_command_proto_rawDescGZIP(), []int{25}
}

func (x *LedgerPage) GetRecords() []*LedgerRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *LedgerPage) GetNextSequence() uint64 {
	if x != nil {
		return x.NextSequence
	}
	return 0
}

type Config struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_app_clientpolicy_command_command_proto_rawDescGZIP(), []int{26}
}

var File_app_clientpolicy_command_command_proto protoreflect.FileDescriptor

const file_app_clientpolicy_command_command_proto_rawDesc = "" +
	"\n" +
	"&app/clientpolicy/command/command.proto\x12 xray.app.clientpolicy.command.v1\x1a\x1dapp/clientpolicy/config.proto\"\a\n" +
	"\x05Empty\"\x85\x01\n" +
	"\rClientRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x126\n" +
	"\x17expected_policy_version\x18\x02 \x01(\x04R\x15expectedPolicyVersion\x12\x1f\n" +
	"\vinbound_tag\x18\x03 \x01(\tR\n" +
	"inboundTag\"\xfa\x01\n" +
	"\fCapabilities\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\rR\n" +
	"apiVersion\x12!\n" +
	"\fcore_version\x18\x02 \x01(\tR\vcoreVersion\x12\x1f\n" +
	"\vinstance_id\x18\x03 \x01(\tR\n" +
	"instanceId\x12\x14\n" +
	"\x05epoch\x18\x04 \x01(\x04R\x05epoch\x12\"\n" +
	"\fcapabilities\x18\x05 \x03(\tR\fcapabilities\x122\n" +
	"\x15reservation_raw_bytes\x18\x06 \x01(\x04R\x13reservationRawBytes\x12\x17\n" +
	"\aboot_id\x18\a \x01(\tR\x06bootId\"E\n" +
	"\x19AuthorityChallengeRequest\x12(\n" +
	"\x10expected_boot_id\x18\x01 \x01(\tR\x0eexpectedBootId\"\xa1\x01\n" +
	"\x12AuthorityChallenge\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x17\n" +
	"\aboot_id\x18\x02 \x01(\tR\x06bootId\x12!\n" +
	"\fchallenge_id\x18\x03 \x01(\tR\vchallengeId\x12.\n" +
	"\x13max_duration_millis\x18\x04 \x01(\x04R\x11maxDurationMillis\"n\n" +
	"\x10AuthorityBinding\x12!\n" +
	"\fauthority_id\x18\x01 \x01(\tR\vauthorityId\x12\x1e\n" +
	"\n" +
	"generation\x18\x02 \x01(\x04R\n" +
	"generation\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\"X\n" +
	"\x0eAuthorityShare\x12\x1c\n" +
	"\tunlimited\x18\x01 \x01(\bR\tunlimited\x12\x12\n" +
	"\x04rate\x18\x02 \x01(\x04R\x04rate\x12\x14\n" +
	"\x05burst\x18\x03 \x01(\x04R\x05burst\"\x92\x01\n" +
	"\x14AuthorityBindRequest\x12(\n" +
	"\x10expected_boot_id\x18\x01 \x01(\tR\x0eexpectedBootId\x12P\n" +
	"\tauthority\x18\x02 \x01(\v22.xray.app.clientpolicy.command.v1.AuthorityBindingR\tauthority\"\xac\x01\n" +
	"\x18AuthorityRequestsRequest\x12(\n" +
	"\x10expected_boot_id\x18\x01 \x01(\tR\x0eexpectedBootId\x12P\n" +
	"\tauthority\x18\x02 \x01(\v22.xray.app.clientpolicy.command.v1.AuthorityBindingR\tauthority\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\"\xa1\x01\n" +
	"\x10AuthorityRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12%\n" +
	"\x0epolicy_version\x18\x03 \x01(\x04R\rpolicyVersion\x12*\n" +
	"\x11previous_grant_id\x18\x04 \x01(\tR\x0fpreviousGrantId\"\x9d\x01\n" +
	"\x11AuthorityRequests\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x17\n" +
	"\aboot_id\x18\x02 \x01(\tR\x06bootId\x12N\n" +
	"\brequests\x18\x03 \x03(\v22.xray.app.clientpolicy.command.v1.AuthorityRequestR\brequests\"\xbf\x04\n" +
	"\x0eExecutionGrant\x12P\n" +
	"\tauthority\x18\x01 \x01(\v22.xray.app.clientpolicy.command.v1.AuthorityBindingR\tauthority\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\x12\x17\n" +
	"\aboot_id\x18\x03 \x01(\tR\x06bootId\x12\x1b\n" +
	"\tclient_id\x18\x04 \x01(\tR\bclientId\x12\x1b\n" +
	"\twindow_id\x18\x05 \x01(\tR\bwindowId\x12%\n" +
	"\x0epolicy_version\x18\x06 \x01(\x04R\rpolicyVersion\x12\x19\n" +
	"\bgrant_id\x18\a \x01(\tR\agrantId\x12\x1a\n" +
	"\bsequence\x18\b \x01(\x04R\bsequence\x12!\n" +
	"\fchallenge_id\x18\t \x01(\tR\vchallengeId\x12\x1a\n" +
	"\bcapacity\x18\n" +
	" \x01(\x04R\bcapacity\x12H\n" +
	"\x06upload\x18\v \x01(\v20.xray.app.clientpolicy.command.v1.AuthorityShareR\x06upload\x12L\n" +
	"\bdownload\x18\f \x01(\v20.xray.app.clientpolicy.command.v1.AuthorityShareR\bdownload\x122\n" +
	"\x15lease_duration_millis\x18\r \x01(\x04R\x13leaseDurationMillis\"\xa6\x01\n" +
	"\x15AuthorityGrantRequest\x12(\n" +
	"\x10expected_boot_id\x18\x01 \x01(\tR\x0eexpectedBootId\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12\x19\n" +
	"\bgrant_id\x18\x03 \x01(\tR\agrantId\x12+\n" +
	"\x11preserve_sessions\x18\x04 \x01(\bR\x10preserveSessions\"\xee\x01\n" +
	"\x17AuthorityRenewalRequest\x12(\n" +
	"\x10expected_boot_id\x18\x01 \x01(\tR\x0eexpectedBootId\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12\x19\n" +
	"\bgrant_id\x18\x03 \x01(\tR\agrantId\x12!\n" +
	"\fchallenge_id\x18\x04 \x01(\tR\vchallengeId\x12\x1a\n" +
	"\bsequence\x18\x05 \x01(\x04R\bsequence\x122\n" +
	"\x15lease_duration_millis\x18\x06 \x01(\x04R\x13leaseDurationMillis\"\xd0\x01\n" +
	"\x13ExecutionGrantState\x12F\n" +
	"\x05grant\x18\x01 \x01(\v20.xray.app.clientpolicy.command.v1.ExecutionGrantR\x05grant\x12=\n" +
	"\x05usage\x18\x02 \x01(\v2'.xray.app.clientpolicy.command.v1.UsageR\x05usage\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x04R\bsequence\x12\x16\n" +
	"\x06sealed\x18\x04 \x01(\bR\x06sealed\"\x8a\x01\n" +
	"\x05Usage\x12\x1d\n" +
	"\n" +
	"raw_upload\x18\x01 \x01(\x04R\trawUpload\x12!\n" +
	"\fraw_download\x18\x02 \x01(\x04R\vrawDownload\x12!\n" +
	"\fbilled_bytes\x18\x03 \x01(\x04R\vbilledBytes\x12\x1c\n" +
	"\tremainder\x18\x04 \x01(\x04R\tremainder\"\xd1\x02\n" +
	"\vClientState\x12;\n" +
	"\x06policy\x18\x01 \x01(\v2#.xray.app.clientpolicy.PolicyConfigR\x06policy\x12=\n" +
	"\x05usage\x18\x02 \x01(\v2'.xray.app.clientpolicy.command.v1.UsageR\x05usage\x12'\n" +
	"\x0funcertain_bytes\x18\x03 \x01(\x04R\x0euncertainBytes\x12\x18\n" +
	"\areasons\x18\x04 \x01(\rR\areasons\x12'\n" +
	"\x0factive_sessions\x18\x05 \x01(\rR\x0eactiveSessions\x12\"\n" +
	"\rfirst_used_at\x18\x06 \x01(\x03R\vfirstUsedAt\x126\n" +
	"\x17authority_grant_history\x18\a \x01(\bR\x15authorityGrantHistory\"O\n" +
	"\fApplyRequest\x12?\n" +
	"\bpolicies\x18\x01 \x03(\v2#.xray.app.clientpolicy.PolicyConfigR\bpolicies\"\x8f\x01\n" +
	"\x11InitializeRequest\x12;\n" +
	"\x06policy\x18\x01 \x01(\v2#.xray.app.clientpolicy.PolicyConfigR\x06policy\x12=\n" +
	"\x05usage\x18\x02 \x01(\v2'.xray.app.clientpolicy.command.v1.UsageR\x05usage\"\x9d\x01\n" +
	"\x15ReconcileUsageRequest\x12(\n" +
	"\x10expected_boot_id\x18\x01 \x01(\tR\x0eexpectedBootId\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12=\n" +
	"\x05usage\x18\x03 \x01(\v2'.xray.app.clientpolicy.command.v1.UsageR\x05usage\"\xf6\x01\n" +
	"\n" +
	"Connection\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\x04R\tsessionId\x12\x1f\n" +
	"\vinbound_tag\x18\x02 \x01(\tR\n" +
	"inboundTag\x123\n" +
	"\x15authenticated_account\x18\x03 \x01(\tR\x14authenticatedAccount\x12'\n" +
	"\x0foriginal_target\x18\x04 \x01(\tR\x0eoriginalTarget\x12#\n" +
	"\ractual_target\x18\x05 \x01(\tR\factualTarget\x12%\n" +
	"\x0epolicy_version\x18\x06 \x01(\x04R\rpolicyVersion\"]\n" +
	"\vConnections\x12N\n" +
	"\vconnections\x18\x01 \x03(\v2,.xray.app.clientpolicy.command.v1.ConnectionR\vconnections\"%\n" +
	"\vCloseResult\x12\x16\n" +
	"\x06closed\x18\x01 \x01(\rR\x06closed\"L\n" +
	"\rLedgerRequest\x12%\n" +
	"\x0eafter_sequence\x18\x01 \x01(\x04R\rafterSequence\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\"\xf2\x02\n" +
	"\fLedgerRecord\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\x04R\x05epoch\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x04R\bsequence\x12\x1b\n" +
	"\tclient_id\x18\x04 \x01(\tR\bclientId\x12%\n" +
	"\x0epolicy_version\x18\x05 \x01(\x04R\rpolicyVersion\x12=\n" +
	"\x05usage\x18\x06 \x01(\v2'.xray.app.clientpolicy.command.v1.UsageR\x05usage\x12'\n" +
	"\x0funcertain_bytes\x18\a \x01(\x04R\x0euncertainBytes\x12%\n" +
	"\x0ereserved_bytes\x18\b \x01(\x04R\rreservedBytes\x12\x18\n" +
	"\arevoked\x18\t \x01(\bR\arevoked\x12\"\n" +
	"\rfirst_used_at\x18\n" +
	" \x01(\x03R\vfirstUsedAt\"{\n" +
	"\n" +
	"LedgerPage\x12H\n" +
	"\arecords\x18\x01 \x03(\v2..xray.app.clientpolicy.command.v1.LedgerRecordR\arecords\x12#\n" +
	"\rnext_sequence\x18\x02 \x01(\x04R\fnextSequence\"\b\n" +
	"\x06Config2\xf2\x10\n" +
	"\x13ClientPolicyService\x12j\n" +
	"\x0fGetCapabilities\x12'.xray.app.clientpolicy.command.v1.Empty\x1a..xray.app.clientpolicy.command.v1.Capabilities\x12\x8a\x01\n" +
	"\x15GetAuthorityChallenge\x12;.xray.app.clientpolicy.command.v1.AuthorityChallengeRequest\x1a4.xray.app.clientpolicy.command.v1.AuthorityChallenge\x12p\n" +
	"\rBindAuthority\x126.xray.app.clientpolicy.command.v1.AuthorityBindRequest\x1a'.xray.app.clientpolicy.command.v1.Empty\x12z\n" +
	"\x17EnableAuthorityRequests\x126.xray.app.clientpolicy.command.v1.AuthorityBindRequest\x1a'.xray.app.clientpolicy.command.v1.Empty\x12\x88\x01\n" +
	"\x15ReadAuthorityRequests\x12:.xray.app.clientpolicy.command.v1.AuthorityRequestsRequest\x1a3.xray.app.clientpolicy.command.v1.AuthorityRequests\x12\x80\x01\n" +
	"\x15InstallAuthorityGrant\x120.xray.app.clientpolicy.command.v1.ExecutionGrant\x1a5.xray.app.clientpolicy.command.v1.ExecutionGrantState\x12\x83\x01\n" +
	"\x11GetAuthorityGrant\x127.xray.app.clientpolicy.command.v1.AuthorityGrantRequest\x1a5.xray.app.clientpolicy.command.v1.ExecutionGrantState\x12\x84\x01\n" +
	"\x12SealAuthorityGrant\x127.xray.app.clientpolicy.command.v1.AuthorityGrantRequest\x1a5.xray.app.clientpolicy.command.v1.ExecutionGrantState\x12y\n" +
	"\x13RenewAuthorityGrant\x129.xray.app.clientpolicy.command.v1.AuthorityRenewalRequest\x1a'.xray.app.clientpolicy.command.v1.Empty\x12k\n" +
	"\tGetClient\x12/.xray.app.clientpolicy.command.v1.ClientRequest\x1a-.xray.app.clientpolicy.command.v1.ClientState\x12h\n" +
	"\rApplyPolicies\x12..xray.app.clientpolicy.command.v1.ApplyRequest\x1a'.xray.app.clientpolicy.command.v1.Empty\x12p\n" +
	"\x10InitializeClient\x123.xray.app.clientpolicy.command.v1.InitializeRequest\x1a'.xray.app.clientpolicy.command.v1.Empty\x12r\n" +
	"\x0eReconcileUsage\x127.xray.app.clientpolicy.command.v1.ReconcileUsageRequest\x1a'.xray.app.clientpolicy.command.v1.Empty\x12h\n" +
	"\fRevokeClient\x12/.xray.app.clientpolicy.command.v1.ClientRequest\x1a'.xray.app.clientpolicy.command.v1.Empty\x12q\n" +
	"\x0fListConnections\x12/.xray.app.clientpolicy.command.v1.ClientRequest\x1a-.xray.app.clientpolicy.command.v1.Connections\x12r\n" +
	"\x10CloseConnections\x12/.xray.app.clientpolicy.command.v1.ClientRequest\x1a-.xray.app.clientpolicy.command.v1.CloseResult\x12c\n" +
	"\x0fCheckpointUsage\x12'.xray.app.clientpolicy.command.v1.Empty\x1a'.xray.app.clientpolicy.command.v1.Empty\x12k\n" +
	"\n" +
	"ReadLedger\x12/.xray.app.clientpolicy.command.v1.LedgerRequest\x1a,.xray.app.clientpolicy.command.v1.LedgerPageB4Z2github.com/xtls/xray-core/app/clientpolicy/commandb\x06proto3"

var (
	file_app_clientpolicy_command_command_proto_rawDescOnce sync.Once
	file_app_clientpolicy_command_command_proto_rawDescData []byte
)

func file_app_clientpolicy_command_command_proto_rawDescGZIP() []byte {
	file_app_clientpolicy_command_command_proto_rawDescOnce.Do(func() {
		file_app_clientpolicy_command_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_clientpolicy_command_command_proto_rawDesc), len(file_app_clientpolicy_command_command_proto_rawDesc)))
	})
	return file_app_clientpolicy_command_command_proto_rawDescData
}

var file_app_clientpolicy_command_command_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_app_clientpolicy_command_command_proto_goTypes = []any{
	(*Empty)(nil),                     // 0: xray.app.clientpolicy.command.v1.Empty
	(*ClientRequest)(nil),             // 1: xray.app.clientpolicy.command.v1.ClientRequest
	(*Capabilities)(nil),              // 2: xray.app.clientpolicy.command.v1.Capabilities
	(*AuthorityChallengeRequest)(nil), // 3: xray.app.clientpolicy.command.v1.AuthorityChallengeRequest
	(*AuthorityChallenge)(nil),        // 4: xray.app.clientpolicy.command.v1.AuthorityChallenge
	(*AuthorityBinding)(nil),          // 5: xray.app.clientpolicy.command.v1.AuthorityBinding
	(*AuthorityShare)(nil),            // 6: xray.app.clientpolicy.command.v1.AuthorityShare
	(*AuthorityBindRequest)(nil),      // 7: xray.app.clientpolicy.command.v1.AuthorityBindRequest
	(*AuthorityRequestsRequest)(nil),  // 8: xray.app.clientpolicy.command.v1.AuthorityRequestsRequest
	(*AuthorityRequest)(nil),          // 9: xray.app.clientpolicy.command.v1.AuthorityRequest
	(*AuthorityRequests)(nil),         // 10: xray.app.clientpolicy.command.v1.AuthorityRequests
	(*ExecutionGrant)(nil),            // 11: xray.app.clientpolicy.command.v1.ExecutionGrant
	(*AuthorityGrantRequest)(nil),     // 12: xray.app.clientpolicy.command.v1.AuthorityGrantRequest
	(*AuthorityRenewalRequest)(nil),   // 13: xray.app.clientpolicy.command.v1.AuthorityRenewalRequest
	(*ExecutionGrantState)(nil),       // 14: xray.app.clientpolicy.command.v1.ExecutionGrantState
	(*Usage)(nil),                     // 15: xray.app.clientpolicy.command.v1.Usage
	(*ClientState)(nil),               // 16: xray.app.clientpolicy.command.v1.ClientState
	(*ApplyRequest)(nil),              // 17: xray.app.clientpolicy.command.v1.ApplyRequest
	(*InitializeRequest)(nil),         // 18: xray.app.clientpolicy.command.v1.InitializeRequest
	(*ReconcileUsageRequest)(nil),     // 19: xray.app.clientpolicy.command.v1.ReconcileUsageRequest
	(*Connection)(nil),                // 20: xray.app.clientpolicy.command.v1.Connection
	(*Connections)(nil),               // 21: xray.app.clientpolicy.command.v1.Connections
	(*CloseResult)(nil),               // 22: xray.app.clientpolicy.command.v1.CloseResult
	(*LedgerRequest)(nil),             // 23: xray.app.clientpolicy.command.v1.LedgerRequest
	(*LedgerRecord)(nil),              // 24: xray.app.clientpolicy.command.v1.LedgerRecord
	(*LedgerPage)(nil),                // 25: xray.app.clientpolicy.command.v1.LedgerPage
	(*Config)(nil),                    // 26: xray.app.clientpolicy.command.v1.Config
	(*clientpolicy.PolicyConfig)(nil), // 27: xray.app.clientpolicy.PolicyConfig
}
var file_app_clientpolicy_command_command_proto_depIdxs = []int32{
	5,  // 0: xray.app.clientpolicy.command.v1.AuthorityBindRequest.authority:type_name -> xray.app.clientpolicy.command.v1.AuthorityBinding
	5,  // 1: xray.app.clientpolicy.command.v1.AuthorityRequestsRequest.authority:type_name -> xray.app.clientpolicy.command.v1.AuthorityBinding
	9,  // 2: xray.app.clientpolicy.command.v1.AuthorityRequests.requests:type_name -> xray.app.clientpolicy.command.v1.AuthorityRequest
	5,  // 3: xray.app.clientpolicy.command.v1.ExecutionGrant.authority:type_name -> xray.app.clientpolicy.command.v1.AuthorityBinding
	6,  // 4: xray.app.clientpolicy.command.v1.ExecutionGrant.upload:type_name -> xray.app.clientpolicy.command.v1.AuthorityShare
	6,  // 5: xray.app.clientpolicy.command.v1.ExecutionGrant.download:type_name -> xray.app.clientpolicy.command.v1.AuthorityShare
	11, // 6: xray.app.clientpolicy.command.v1.ExecutionGrantState.grant:type_name -> xray.app.clientpolicy.command.v1.ExecutionGrant
	15, // 7: xray.app.clientpolicy.command.v1.ExecutionGrantState.usage:type_name -> xray.app.clientpolicy.command.v1.Usage
	27, // 8: xray.app.clientpolicy.command.v1.ClientState.policy:type_name -> xray.app.clientpolicy.PolicyConfig
	15, // 9: xray.app.clientpolicy.command.v1.ClientState.usage:type_name -> xray.app.clientpolicy.command.v1.Usage
	27, // 10: xray.app.clientpolicy.command.v1.ApplyRequest.policies:type_name -> xray.app.clientpolicy.PolicyConfig
	27, // 11: xray.app.clientpolicy.command.v1.InitializeRequest.policy:type_name -> xray.app.clientpolicy.PolicyConfig
	15, // 12: xray.app.clientpolicy.command.v1.InitializeRequest.usage:type_name -> xray.app.clientpolicy.command.v1.Usage
	15, // 13: xray.app.clientpolicy.command.v1.ReconcileUsageRequest.usage:type_name -> xray.app.clientpolicy.command.v1.Usage
	20, // 14: xray.app.clientpolicy.command.v1.Connections.connections:type_name -> xray.app.clientpolicy.command.v1.Connection
	15, // 15: xray.app.clientpolicy.command.v1.LedgerRecord.usage:type_name -> xray.app.clientpolicy.command.v1.Usage
	24, // 16: xray.app.clientpolicy.command.v1.LedgerPage.records:type_name -> xray.app.clientpolicy.command.v1.LedgerRecord
	0,  // 17: xray.app.clientpolicy.command.v1.ClientPolicyService.GetCapabilities:input_type -> xray.app.clientpolicy.command.v1.Empty
	3,  // 18: xray.app.clientpolicy.command.v1.ClientPolicyService.GetAuthorityChallenge:input_type -> xray.app.clientpolicy.command.v1.AuthorityChallengeRequest
	7,  // 19: xray.app.clientpolicy.command.v1.ClientPolicyService.BindAuthority:input_type -> xray.app.clientpolicy.command.v1.AuthorityBindRequest
	7,  // 20: xray.app.clientpolicy.command.v1.ClientPolicyService.EnableAuthorityRequests:input_type -> xray.app.clientpolicy.command.v1.AuthorityBindRequest
	8,  // 21: xray.app.clientpolicy.command.v1.ClientPolicyService.ReadAuthorityRequests:input_type -> xray.app.clientpolicy.command.v1.AuthorityRequestsRequest
	11, // 22: xray.app.clientpolicy.command.v1.ClientPolicyService.InstallAuthorityGrant:input_type -> xray.app.clientpolicy.command.v1.ExecutionGrant
	12, // 23: xray.app.clientpolicy.command.v1.ClientPolicyService.GetAuthorityGrant:input_type -> xray.app.clientpolicy.command.v1.AuthorityGrantRequest
	12, // 24: xray.app.clientpolicy.command.v1.ClientPolicyService.SealAuthorityGrant:input_type -> xray.app.clientpolicy.command.v1.AuthorityGrantRequest
	13, // 25: xray.app.clientpolicy.command.v1.ClientPolicyService.RenewAuthorityGrant:input_type -> xray.app.clientpolicy.command.v1.AuthorityRenewalRequest
	1,  // 26: xray.app.clientpolicy.command.v1.ClientPolicyService.GetClient:input_type -> xray.app.clientpolicy.command.v1.ClientRequest
	17, // 27: xray.app.clientpolicy.command.v1.ClientPolicyService.ApplyPolicies:input_type -> xray.app.clientpolicy.command.v1.ApplyRequest
	18, // 28: xray.app.clientpolicy.command.v1.ClientPolicyService.InitializeClient:input_type -> xray.app.clientpolicy.command.v1.InitializeRequest
	19, // 29: xray.app.clientpolicy.command.v1.ClientPolicyService.ReconcileUsage:input_type -> xray.app.clientpolicy.command.v1.ReconcileUsageRequest
	1,  // 30: xray.app.clientpolicy.command.v1.ClientPolicyService.RevokeClient:input_type -> xray.app.clientpolicy.command.v1.ClientRequest
	1,  // 31: xray.app.clientpolicy.command.v1.ClientPolicyService.ListConnections:input_type -> xray.app.clientpolicy.command.v1.ClientRequest
	1,  // 32: xray.app.clientpolicy.command.v1.ClientPolicyService.CloseConnections:input_type -> xray.app.clientpolicy.command.v1.ClientRequest
	0,  // 33: xray.app.clientpolicy.command.v1.ClientPolicyService.CheckpointUsage:input_type -> xray.app.clientpolicy.command.v1.Empty
	23, // 34: xray.app.clientpolicy.command.v1.ClientPolicyService.ReadLedger:input_type -> xray.app.clientpolicy.command.v1.LedgerRequest
	2,  // 35: xray.app.clientpolicy.command.v1.ClientPolicyService.GetCapabilities:output_type -> xray.app.clientpolicy.command.v1.Capabilities
	4,  // 36: xray.app.clientpolicy.command.v1.ClientPolicyService.GetAuthorityChallenge:output_type -> xray.app.clientpolicy.command.v1.AuthorityChallenge
	0,  // 37: xray.app.clientpolicy.command.v1.ClientPolicyService.BindAuthority:output_type -> xray.app.clientpolicy.command.v1.Empty
	0,  // 38: xray.app.clientpolicy.command.v1.ClientPolicyService.EnableAuthorityRequests:output_type -> xray.app.clientpolicy.command.v1.Empty
	10, // 39: xray.app.clientpolicy.command.v1.ClientPolicyService.ReadAuthorityRequests:output_type -> xray.app.clientpolicy.command.v1.AuthorityRequests
	14, // 40: xray.app.clientpolicy.command.v1.ClientPolicyService.InstallAuthorityGrant:output_type -> xray.app.clientpolicy.command.v1.ExecutionGrantState
	14, // 41: xray.app.clientpolicy.command.v1.ClientPolicyService.GetAuthorityGrant:output_type -> xray.app.clientpolicy.command.v1.ExecutionGrantState
	14, // 42: xray.app.clientpolicy.command.v1.ClientPolicyService.SealAuthorityGrant:output_type -> xray.app.clientpolicy.command.v1.ExecutionGrantState
	0,  // 43: xray.app.clientpolicy.command.v1.ClientPolicyService.RenewAuthorityGrant:output_type -> xray.app.clientpolicy.command.v1.Empty
	16, // 44: xray.app.clientpolicy.command.v1.ClientPolicyService.GetClient:output_type -> xray.app.clientpolicy.command.v1.ClientState
	0,  // 45: xray.app.clientpolicy.command.v1.ClientPolicyService.ApplyPolicies:output_type -> xray.app.clientpolicy.command.v1.Empty
	0,  // 46: xray.app.clientpolicy.command.v1.ClientPolicyService.InitializeClient:output_type -> xray.app.clientpolicy.command.v1.Empty
	0,  // 47: xray.app.clientpolicy.command.v1.ClientPolicyService.ReconcileUsage:output_type -> xray.app.clientpolicy.command.v1.Empty
	0,  // 48: xray.app.clientpolicy.command.v1.ClientPolicyService.RevokeClient:output_type -> xray.app.clientpolicy.command.v1.Empty
	21, // 49: xray.app.clientpolicy.command.v1.ClientPolicyService.ListConnections:output_type -> xray.app.clientpolicy.command.v1.Connections
	22, // 50: xray.app.clientpolicy.command.v1.ClientPolicyService.CloseConnections:output_type -> xray.app.clientpolicy.command.v1.CloseResult
	0,  // 51: xray.app.clientpolicy.command.v1.ClientPolicyService.CheckpointUsage:output_type -> xray.app.clientpolicy.command.v1.Empty
	25, // 52: xray.app.clientpolicy.command.v1.ClientPolicyService.ReadLedger:output_type -> xray.app.clientpolicy.command.v1.LedgerPage
	35, // [35:53] is the sub-list for method output_type
	17, // [17:35] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_app_clientpolicy_command_command_proto_init() }
func file_app_clientpolicy_command_command_proto_init() {
	if File_app_clientpolicy_command_command_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_clientpolicy_command_command_proto_rawDesc), len(file_app_clientpolicy_command_command_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_clientpolicy_command_command_proto_goTypes,
		DependencyIndexes: file_app_clientpolicy_command_command_proto_depIdxs,
		MessageInfos:      file_app_clientpolicy_command_command_proto_msgTypes,
	}.Build()
	File_app_clientpolicy_command_command_proto = out.File
	file_app_clientpolicy_command_command_proto_goTypes = nil
	file_app_clientpolicy_command_command_proto_depIdxs = nil
}
