// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v7.36.2
// source: app/clientpolicy/command/command.proto

package command

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClientPolicyService_GetCapabilities_FullMethodName         = "/xray.app.clientpolicy.command.v1.ClientPolicyService/GetCapabilities"
	ClientPolicyService_GetAuthorityChallenge_FullMethodName   = "/xray.app.clientpolicy.command.v1.ClientPolicyService/GetAuthorityChallenge"
	ClientPolicyService_BindAuthority_FullMethodName           = "/xray.app.clientpolicy.command.v1.ClientPolicyService/BindAuthority"
	ClientPolicyService_EnableAuthorityRequests_FullMethodName = "/xray.app.clientpolicy.command.v1.ClientPolicyService/EnableAuthorityRequests"
	ClientPolicyService_ReadAuthorityRequests_FullMethodName   = "/xray.app.clientpolicy.command.v1.ClientPolicyService/ReadAuthorityRequests"
	ClientPolicyService_InstallAuthorityGrant_FullMethodName   = "/xray.app.clientpolicy.command.v1.ClientPolicyService/InstallAuthorityGrant"
	ClientPolicyService_GetAuthorityGrant_FullMethodName       = "/xray.app.clientpolicy.command.v1.ClientPolicyService/GetAuthorityGrant"
	ClientPolicyService_SealAuthorityGrant_FullMethodName      = "/xray.app.clientpolicy.command.v1.ClientPolicyService/SealAuthorityGrant"
	ClientPolicyService_RenewAuthorityGrant_FullMethodName     = "/xray.app.clientpolicy.command.v1.ClientPolicyService/RenewAuthorityGrant"
	ClientPolicyService_GetClient_FullMethodName               = "/xray.app.clientpolicy.command.v1.ClientPolicyService/GetClient"
	ClientPolicyService_ApplyPolicies_FullMethodName           = "/xray.app.clientpolicy.command.v1.ClientPolicyService/ApplyPolicies"
	ClientPolicyService_InitializeClient_FullMethodName        = "/xray.app.clientpolicy.command.v1.ClientPolicyService/InitializeClient"
	ClientPolicyService_ReconcileUsage_FullMethodName          = "/xray.app.clientpolicy.command.v1.ClientPolicyService/ReconcileUsage"
	ClientPolicyService_RevokeClient_FullMethodName            = "/xray.app.clientpolicy.command.v1.ClientPolicyService/RevokeClient"
	ClientPolicyService_ListConnections_FullMethodName         = "/xray.app.clientpolicy.command.v1.ClientPolicyService/ListConnections"
	ClientPolicyService_CloseConnections_FullMethodName        = "/xray.app.clientpolicy.command.v1.ClientPolicyService/CloseConnections"
	ClientPolicyService_CheckpointUsage_FullMethodName         = "/xray.app.clientpolicy.command.v1.ClientPolicyService/CheckpointUsage"
	ClientPolicyService_ReadLedger_FullMethodName              = "/xray.app.clientpolicy.command.v1.ClientPolicyService/ReadLedger"
)

// ClientPolicyServiceClient is the client API for ClientPolicyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClientPolicyServiceClient interface {
	GetCapabilities(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Capabilities, error)
	GetAuthorityChallenge(ctx context.Context, in *AuthorityChallengeRequest, opts ...grpc.CallOption) (*AuthorityChallenge, error)
	BindAuthority(ctx context.Context, in *AuthorityBindRequest, opts ...grpc.CallOption) (*Empty, error)
	EnableAuthorityRequests(ctx context.Context, in *AuthorityBindRequest, opts ...grpc.CallOption) (*Empty, error)
	ReadAuthorityRequests(ctx context.Context, in *AuthorityRequestsRequest, opts ...grpc.CallOption) (*AuthorityRequests, error)
	InstallAuthorityGrant(ctx context.Context, in *ExecutionGrant, opts ...grpc.CallOption) (*ExecutionGrantState, error)
	GetAuthorityGrant(ctx context.Context, in *AuthorityGrantRequest, opts ...grpc.CallOption) (*ExecutionGrantState, error)
	SealAuthorityGrant(ctx context.Context, in *AuthorityGrantRequest, opts ...grpc.CallOption) (*ExecutionGrantState, error)
	RenewAuthorityGrant(ctx context.Context, in *AuthorityRenewalRequest, opts ...grpc.CallOption) (*Empty, error)
	GetClient(ctx context.Context, in *ClientRequest, opts ...grpc.CallOption) (*ClientState, error)
	ApplyPolicies(ctx context.Context, in *ApplyRequest, opts ...grpc.CallOption) (*Empty, error)
	InitializeClient(ctx context.Context, in *InitializeRequest, opts ...grpc.CallOption) (*Empty, error)
	ReconcileUsage(ctx context.Context, in *ReconcileUsageRequest, opts ...grpc.CallOption) (*Empty, error)
	RevokeClient(ctx context.Context, in *ClientRequest, opts ...grpc.CallOption) (*Empty, error)
	ListConnections(ctx context.Context, in *ClientRequest, opts ...grpc.CallOption) (*Connections, error)
	CloseConnections(ctx context.Context, in *ClientRequest, opts ...grpc.CallOption) (*CloseResult, error)
	CheckpointUsage(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	ReadLedger(ctx context.Context, in *LedgerRequest, opts ...grpc.CallOption) (*LedgerPage, error)
}

type clientPolicyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClientPolicyServiceClient(cc grpc.ClientConnInterface) ClientPolicyServiceClient {
	return &clientPolicyServiceClient{cc}
}

func (c *clientPolicyServiceClient) GetCapabilities(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Capabilities, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Capabilities)
	err := c.cc.Invoke(ctx, ClientPolicyService_GetCapabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientPolicyServiceClient) GetAuthorityChallenge(ctx context.Context, in *AuthorityChallengeRequest, opts ...grpc.CallOption) (*AuthorityChallenge, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthorityChallenge)
	err := c.cc.Invoke(ctx, ClientPolicyService_GetAuthorityChallenge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientPolicyServiceClient) BindAuthority(ctx context.Context, in *AuthorityBindRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ClientPolicyService_BindAuthority_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientPolicyServiceClient) EnableAuthorityRequests(ctx context.Context, in *AuthorityBindRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ClientPolicyService_EnableAuthorityRequests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientPolicyServiceClient) ReadAuthorityRequests(ctx context.Context, in *AuthorityRequestsRequest, opts ...grpc.CallOption) (*AuthorityRequests, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthorityRequests)
	err := c.cc.Invoke(ctx, ClientPolicyService_ReadAuthorityRequests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientPolicyServiceClient) InstallAuthorityGrant(ctx context.Context, in *ExecutionGrant, opts ...grpc.CallOption) (*ExecutionGrantState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecutionGrantState)
	err := c.cc.Invoke(ctx, ClientPolicyService_InstallAuthorityGrant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientPolicyServiceClient) GetAuthorityGrant(ctx context.Context, in *AuthorityGrantRequest, opts ...grpc.CallOption) (*ExecutionGrantState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecutionGrantState)
	err := c.cc.Invoke(ctx, ClientPolicyService_GetAuthorityGrant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientPolicyServiceClient) SealAuthorityGrant(ctx context.Context, in *AuthorityGrantRequest, opts ...grpc.CallOption) (*ExecutionGrantState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecutionGrantState)
	err := c.cc.Invoke(ctx, ClientPolicyService_SealAuthorityGrant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientPolicyServiceClient) RenewAuthorityGrant(ctx context.Context, in *AuthorityRenewalRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ClientPolicyService_RenewAuthorityGrant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientPolicyServiceClient) GetClient(ctx context.Context, in *ClientRequest, opts ...grpc.CallOption) (*ClientState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClientState)
	err := c.cc.Invoke(ctx, ClientPolicyService_GetClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientPolicyServiceClient) ApplyPolicies(ctx context.Context, in *ApplyRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ClientPolicyService_ApplyPolicies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientPolicyServiceClient) InitializeClient(ctx context.Context, in *InitializeRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ClientPolicyService_InitializeClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientPolicyServiceClient) ReconcileUsage(ctx context.Context, in *ReconcileUsageRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ClientPolicyService_ReconcileUsage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientPolicyServiceClient) RevokeClient(ctx context.Context, in *ClientRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ClientPolicyService_RevokeClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientPolicyServiceClient) ListConnections(ctx context.Context, in *ClientRequest, opts ...grpc.CallOption) (*Connections, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Connections)
	err := c.cc.Invoke(ctx, ClientPolicyService_ListConnections_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientPolicyServiceClient) CloseConnections(ctx context.Context, in *ClientRequest, opts ...grpc.CallOption) (*CloseResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseResult)
	err := c.cc.Invoke(ctx, ClientPolicyService_CloseConnections_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientPolicyServiceClient) CheckpointUsage(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ClientPolicyService_CheckpointUsage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientPolicyServiceClient) ReadLedger(ctx context.Context, in *LedgerRequest, opts ...grpc.CallOption) (*LedgerPage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LedgerPage)
	err := c.cc.Invoke(ctx, ClientPolicyService_ReadLedger_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientPolicyServiceServer is the server API for ClientPolicyService service.
// All implementations must embed UnimplementedClientPolicyServiceServer
// for forward compatibility.
type ClientPolicyServiceServer interface {
	GetCapabilities(context.Context, *Empty) (*Capabilities, error)
	GetAuthorityChallenge(context.Context, *AuthorityChallengeRequest) (*AuthorityChallenge, error)
	BindAuthority(context.Context, *AuthorityBindRequest) (*Empty, error)
	EnableAuthorityRequests(context.Context, *AuthorityBindRequest) (*Empty, error)
	ReadAuthorityRequests(context.Context, *AuthorityRequestsRequest) (*AuthorityRequests, error)
	InstallAuthorityGrant(context.Context, *ExecutionGrant) (*ExecutionGrantState, error)
	GetAuthorityGrant(context.Context, *AuthorityGrantRequest) (*ExecutionGrantState, error)
	SealAuthorityGrant(context.Context, *AuthorityGrantRequest) (*ExecutionGrantState, error)
	RenewAuthorityGrant(context.Context, *AuthorityRenewalRequest) (*Empty, error)
	GetClient(context.Context, *ClientRequest) (*ClientState, error)
	ApplyPolicies(context.Context, *ApplyRequest) (*Empty, error)
	InitializeClient(context.Context, *InitializeRequest) (*Empty, error)
	ReconcileUsage(context.Context, *ReconcileUsageRequest) (*Empty, error)
	RevokeClient(context.Context, *ClientRequest) (*Empty, error)
	ListConnections(context.Context, *ClientRequest) (*Connections, error)
	CloseConnections(context.Context, *ClientRequest) (*CloseResult, error)
	CheckpointUsage(context.Context, *Empty) (*Empty, error)
	ReadLedger(context.Context, *LedgerRequest) (*LedgerPage, error)
	mustEmbedUnimplementedClientPolicyServiceServer()
}

// UnimplementedClientPolicyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClientPolicyServiceServer struct{}

func (UnimplementedClientPolicyServiceServer) GetCapabilities(context.Context, *Empty) (*Capabilities, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCapabilities not implemented")
}
func (UnimplementedClientPolicyServiceServer) GetAuthorityChallenge(context.Context, *AuthorityChallengeRequest) (*AuthorityChallenge, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAuthorityChallenge not implemented")
}
func (UnimplementedClientPolicyServiceServer) BindAuthority(context.Context, *AuthorityBindRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method BindAuthority not implemented")
}
func (UnimplementedClientPolicyServiceServer) EnableAuthorityRequests(context.Context, *AuthorityBindRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method EnableAuthorityRequests not implemented")
}
func (UnimplementedClientPolicyServiceServer) ReadAuthorityRequests(context.Context, *AuthorityRequestsRequest) (*AuthorityRequests, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadAuthorityRequests not implemented")
}
func (UnimplementedClientPolicyServiceServer) InstallAuthorityGrant(context.Context, *ExecutionGrant) (*ExecutionGrantState, error) {
	return nil, status.Error(codes.Unimplemented, "method InstallAuthorityGrant not implemented")
}
func (UnimplementedClientPolicyServiceServer) GetAuthorityGrant(context.Context, *AuthorityGrantRequest) (*ExecutionGrantState, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAuthorityGrant not implemented")
}
func (UnimplementedClientPolicyServiceServer) SealAuthorityGrant(context.Context, *AuthorityGrantRequest) (*ExecutionGrantState, error) {
	return nil, status.Error(codes.Unimplemented, "method SealAuthorityGrant not implemented")
}
func (UnimplementedClientPolicyServiceServer) RenewAuthorityGrant(context.Context, *AuthorityRenewalRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RenewAuthorityGrant not implemented")
}
func (UnimplementedClientPolicyServiceServer) GetClient(context.Context, *ClientRequest) (*ClientState, error) {
	return nil, status.Error(codes.Unimplemented, "method GetClient not implemented")
}
func (UnimplementedClientPolicyServiceServer) ApplyPolicies(context.Context, *ApplyRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyPolicies not implemented")
}
func (UnimplementedClientPolicyServiceServer) InitializeClient(context.Context, *InitializeRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method InitializeClient not implemented")
}
func (UnimplementedClientPolicyServiceServer) ReconcileUsage(context.Context, *ReconcileUsageRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ReconcileUsage not implemented")
}
func (UnimplementedClientPolicyServiceServer) RevokeClient(context.Context, *ClientRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeClient not implemented")
}
func (UnimplementedClientPolicyServiceServer) ListConnections(context.Context, *ClientRequest) (*Connections, error) {
	return nil, status.Error(codes.Unimplemented, "method ListConnections not implemented")
}
func (UnimplementedClientPolicyServiceServer) CloseConnections(context.Context, *ClientRequest) (*CloseResult, error) {
	return nil, status.Error(codes.Unimplemented, "method CloseConnections not implemented")
}
func (UnimplementedClientPolicyServiceServer) CheckpointUsage(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckpointUsage not implemented")
}
func (UnimplementedClientPolicyServiceServer) ReadLedger(context.Context, *LedgerRequest) (*LedgerPage, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadLedger not implemented")
}
func (UnimplementedClientPolicyServiceServer) mustEmbedUnimplementedClientPolicyServiceServer() {}
func (UnimplementedClientPolicyServiceServer) testEmbeddedByValue()                             {}

// UnsafeClientPolicyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClientPolicyServiceServer will
// result in compilation errors.
type UnsafeClientPolicyServiceServer interface {
	mustEmbedUnimplementedClientPolicyServiceServer()
}

func RegisterClientPolicyServiceServer(s grpc.ServiceRegistrar, srv ClientPolicyServiceServer) {
	// If the following call panics, it indicates UnimplementedClientPolicyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClientPolicyService_ServiceDesc, srv)
}

func _ClientPolicyService_GetCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientPolicyServiceServer).GetCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientPolicyService_GetCapabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientPolicyServiceServer).GetCapabilities(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientPolicyService_GetAuthorityChallenge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorityChallengeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientPolicyServiceServer).GetAuthorityChallenge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientPolicyService_GetAuthorityChallenge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientPolicyServiceServer).GetAuthorityChallenge(ctx, req.(*AuthorityChallengeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientPolicyService_BindAuthority_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorityBindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientPolicyServiceServer).BindAuthority(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientPolicyService_BindAuthority_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientPolicyServiceServer).BindAuthority(ctx, req.(*AuthorityBindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientPolicyService_EnableAuthorityRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorityBindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientPolicyServiceServer).EnableAuthorityRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientPolicyService_EnableAuthorityRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientPolicyServiceServer).EnableAuthorityRequests(ctx, req.(*AuthorityBindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientPolicyService_ReadAuthorityRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorityRequestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientPolicyServiceServer).ReadAuthorityRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientPolicyService_ReadAuthorityRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientPolicyServiceServer).ReadAuthorityRequests(ctx, req.(*AuthorityRequestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientPolicyService_InstallAuthorityGrant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecutionGrant)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientPolicyServiceServer).InstallAuthorityGrant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientPolicyService_InstallAuthorityGrant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientPolicyServiceServer).InstallAuthorityGrant(ctx, req.(*ExecutionGrant))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientPolicyService_GetAuthorityGrant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorityGrantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientPolicyServiceServer).GetAuthorityGrant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientPolicyService_GetAuthorityGrant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientPolicyServiceServer).GetAuthorityGrant(ctx, req.(*AuthorityGrantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientPolicyService_SealAuthorityGrant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorityGrantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientPolicyServiceServer).SealAuthorityGrant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientPolicyService_SealAuthorityGrant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientPolicyServiceServer).SealAuthorityGrant(ctx, req.(*AuthorityGrantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientPolicyService_RenewAuthorityGrant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorityRenewalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientPolicyServiceServer).RenewAuthorityGrant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientPolicyService_RenewAuthorityGrant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientPolicyServiceServer).RenewAuthorityGrant(ctx, req.(*AuthorityRenewalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientPolicyService_GetClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientPolicyServiceServer).GetClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientPolicyService_GetClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientPolicyServiceServer).GetClient(ctx, req.(*ClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientPolicyService_ApplyPolicies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientPolicyServiceServer).ApplyPolicies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientPolicyService_ApplyPolicies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientPolicyServiceServer).ApplyPolicies(ctx, req.(*ApplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientPolicyService_InitializeClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitializeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientPolicyServiceServer).InitializeClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientPolicyService_InitializeClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientPolicyServiceServer).InitializeClient(ctx, req.(*InitializeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientPolicyService_ReconcileUsage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReconcileUsageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientPolicyServiceServer).ReconcileUsage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientPolicyService_ReconcileUsage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientPolicyServiceServer).ReconcileUsage(ctx, req.(*ReconcileUsageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientPolicyService_RevokeClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientPolicyServiceServer).RevokeClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientPolicyService_RevokeClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientPolicyServiceServer).RevokeClient(ctx, req.(*ClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientPolicyService_ListConnections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientPolicyServiceServer).ListConnections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientPolicyService_ListConnections_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientPolicyServiceServer).ListConnections(ctx, req.(*ClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientPolicyService_CloseConnections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientPolicyServiceServer).CloseConnections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientPolicyService_CloseConnections_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientPolicyServiceServer).CloseConnections(ctx, req.(*ClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientPolicyService_CheckpointUsage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientPolicyServiceServer).CheckpointUsage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientPolicyService_CheckpointUsage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientPolicyServiceServer).CheckpointUsage(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientPolicyService_ReadLedger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LedgerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientPolicyServiceServer).ReadLedger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientPolicyService_ReadLedger_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientPolicyServiceServer).ReadLedger(ctx, req.(*LedgerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClientPolicyService_ServiceDesc is the grpc.ServiceDesc for ClientPolicyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClientPolicyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xray.app.clientpolicy.command.v1.ClientPolicyService",
	HandlerType: (*ClientPolicyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCapabilities",
			Handler:    _ClientPolicyService_GetCapabilities_Handler,
		},
		{
			MethodName: "GetAuthorityChallenge",
			Handler:    _ClientPolicyService_GetAuthorityChallenge_Handler,
		},
		{
			MethodName: "BindAuthority",
			Handler:    _ClientPolicyService_BindAuthority_Handler,
		},
		{
			MethodName: "EnableAuthorityRequests",
			Handler:    _ClientPolicyService_EnableAuthorityRequests_Handler,
		},
		{
			MethodName: "ReadAuthorityRequests",
			Handler:    _ClientPolicyService_ReadAuthorityRequests_Handler,
		},
		{
			MethodName: "InstallAuthorityGrant",
			Handler:    _ClientPolicyService_InstallAuthorityGrant_Handler,
		},
		{
			MethodName: "GetAuthorityGrant",
			Handler:    _ClientPolicyService_GetAuthorityGrant_Handler,
		},
		{
			MethodName: "SealAuthorityGrant",
			Handler:    _ClientPolicyService_SealAuthorityGrant_Handler,
		},
		{
			MethodName: "RenewAuthorityGrant",
			Handler:    _ClientPolicyService_RenewAuthorityGrant_Handler,
		},
		{
			MethodName: "GetClient",
			Handler:    _ClientPolicyService_GetClient_Handler,
		},
		{
			MethodName: "ApplyPolicies",
			Handler:    _ClientPolicyService_ApplyPolicies_Handler,
		},
		{
			MethodName: "InitializeClient",
			Handler:    _ClientPolicyService_InitializeClient_Handler,
		},
		{
			MethodName: "ReconcileUsage",
			Handler:    _ClientPolicyService_ReconcileUsage_Handler,
		},
		{
			MethodName: "RevokeClient",
			Handler:    _ClientPolicyService_RevokeClient_Handler,
		},
		{
			MethodName: "ListConnections",
			Handler:    _ClientPolicyService_ListConnections_Handler,
		},
		{
			MethodName: "CloseConnections",
			Handler:    _ClientPolicyService_CloseConnections_Handler,
		},
		{
			MethodName: "CheckpointUsage",
			Handler:    _ClientPolicyService_CheckpointUsage_Handler,
		},
		{
			MethodName: "ReadLedger",
			Handler:    _ClientPolicyService_ReadLedger_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/clientpolicy/command/command.proto",
}
