// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v7.36.2
// source: app/clientpolicy/command/command.proto

package command

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClientPolicyService_GetCapabilities_FullMethodName  = "/xray.app.clientpolicy.command.v1.ClientPolicyService/GetCapabilities"
	ClientPolicyService_GetClient_FullMethodName        = "/xray.app.clientpolicy.command.v1.ClientPolicyService/GetClient"
	ClientPolicyService_ApplyPolicies_FullMethodName    = "/xray.app.clientpolicy.command.v1.ClientPolicyService/ApplyPolicies"
	ClientPolicyService_InitializeClient_FullMethodName = "/xray.app.clientpolicy.command.v1.ClientPolicyService/InitializeClient"
	ClientPolicyService_RevokeClient_FullMethodName     = "/xray.app.clientpolicy.command.v1.ClientPolicyService/RevokeClient"
	ClientPolicyService_ListConnections_FullMethodName  = "/xray.app.clientpolicy.command.v1.ClientPolicyService/ListConnections"
	ClientPolicyService_CloseConnections_FullMethodName = "/xray.app.clientpolicy.command.v1.ClientPolicyService/CloseConnections"
	ClientPolicyService_CheckpointUsage_FullMethodName  = "/xray.app.clientpolicy.command.v1.ClientPolicyService/CheckpointUsage"
	ClientPolicyService_ReadLedger_FullMethodName       = "/xray.app.clientpolicy.command.v1.ClientPolicyService/ReadLedger"
)

// ClientPolicyServiceClient is the client API for ClientPolicyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClientPolicyServiceClient interface {
	GetCapabilities(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Capabilities, error)
	GetClient(ctx context.Context, in *ClientRequest, opts ...grpc.CallOption) (*ClientState, error)
	ApplyPolicies(ctx context.Context, in *ApplyRequest, opts ...grpc.CallOption) (*Empty, error)
	InitializeClient(ctx context.Context, in *InitializeRequest, opts ...grpc.CallOption) (*Empty, error)
	RevokeClient(ctx context.Context, in *ClientRequest, opts ...grpc.CallOption) (*Empty, error)
	ListConnections(ctx context.Context, in *ClientRequest, opts ...grpc.CallOption) (*Connections, error)
	CloseConnections(ctx context.Context, in *ClientRequest, opts ...grpc.CallOption) (*CloseResult, error)
	CheckpointUsage(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	ReadLedger(ctx context.Context, in *LedgerRequest, opts ...grpc.CallOption) (*LedgerPage, error)
}

type clientPolicyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClientPolicyServiceClient(cc grpc.ClientConnInterface) ClientPolicyServiceClient {
	return &clientPolicyServiceClient{cc}
}

func (c *clientPolicyServiceClient) GetCapabilities(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Capabilities, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Capabilities)
	err := c.cc.Invoke(ctx, ClientPolicyService_GetCapabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientPolicyServiceClient) GetClient(ctx context.Context, in *ClientRequest, opts ...grpc.CallOption) (*ClientState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClientState)
	err := c.cc.Invoke(ctx, ClientPolicyService_GetClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientPolicyServiceClient) ApplyPolicies(ctx context.Context, in *ApplyRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ClientPolicyService_ApplyPolicies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientPolicyServiceClient) InitializeClient(ctx context.Context, in *InitializeRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ClientPolicyService_InitializeClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientPolicyServiceClient) RevokeClient(ctx context.Context, in *ClientRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ClientPolicyService_RevokeClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientPolicyServiceClient) ListConnections(ctx context.Context, in *ClientRequest, opts ...grpc.CallOption) (*Connections, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Connections)
	err := c.cc.Invoke(ctx, ClientPolicyService_ListConnections_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientPolicyServiceClient) CloseConnections(ctx context.Context, in *ClientRequest, opts ...grpc.CallOption) (*CloseResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseResult)
	err := c.cc.Invoke(ctx, ClientPolicyService_CloseConnections_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientPolicyServiceClient) CheckpointUsage(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ClientPolicyService_CheckpointUsage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientPolicyServiceClient) ReadLedger(ctx context.Context, in *LedgerRequest, opts ...grpc.CallOption) (*LedgerPage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LedgerPage)
	err := c.cc.Invoke(ctx, ClientPolicyService_ReadLedger_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientPolicyServiceServer is the server API for ClientPolicyService service.
// All implementations must embed UnimplementedClientPolicyServiceServer
// for forward compatibility.
type ClientPolicyServiceServer interface {
	GetCapabilities(context.Context, *Empty) (*Capabilities, error)
	GetClient(context.Context, *ClientRequest) (*ClientState, error)
	ApplyPolicies(context.Context, *ApplyRequest) (*Empty, error)
	InitializeClient(context.Context, *InitializeRequest) (*Empty, error)
	RevokeClient(context.Context, *ClientRequest) (*Empty, error)
	ListConnections(context.Context, *ClientRequest) (*Connections, error)
	CloseConnections(context.Context, *ClientRequest) (*CloseResult, error)
	CheckpointUsage(context.Context, *Empty) (*Empty, error)
	ReadLedger(context.Context, *LedgerRequest) (*LedgerPage, error)
	mustEmbedUnimplementedClientPolicyServiceServer()
}

// UnimplementedClientPolicyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClientPolicyServiceServer struct{}

func (UnimplementedClientPolicyServiceServer) GetCapabilities(context.Context, *Empty) (*Capabilities, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCapabilities not implemented")
}
func (UnimplementedClientPolicyServiceServer) GetClient(context.Context, *ClientRequest) (*ClientState, error) {
	return nil, status.Error(codes.Unimplemented, "method GetClient not implemented")
}
func (UnimplementedClientPolicyServiceServer) ApplyPolicies(context.Context, *ApplyRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyPolicies not implemented")
}
func (UnimplementedClientPolicyServiceServer) InitializeClient(context.Context, *InitializeRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method InitializeClient not implemented")
}
func (UnimplementedClientPolicyServiceServer) RevokeClient(context.Context, *ClientRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeClient not implemented")
}
func (UnimplementedClientPolicyServiceServer) ListConnections(context.Context, *ClientRequest) (*Connections, error) {
	return nil, status.Error(codes.Unimplemented, "method ListConnections not implemented")
}
func (UnimplementedClientPolicyServiceServer) CloseConnections(context.Context, *ClientRequest) (*CloseResult, error) {
	return nil, status.Error(codes.Unimplemented, "method CloseConnections not implemented")
}
func (UnimplementedClientPolicyServiceServer) CheckpointUsage(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckpointUsage not implemented")
}
func (UnimplementedClientPolicyServiceServer) ReadLedger(context.Context, *LedgerRequest) (*LedgerPage, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadLedger not implemented")
}
func (UnimplementedClientPolicyServiceServer) mustEmbedUnimplementedClientPolicyServiceServer() {}
func (UnimplementedClientPolicyServiceServer) testEmbeddedByValue()                             {}

// UnsafeClientPolicyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClientPolicyServiceServer will
// result in compilation errors.
type UnsafeClientPolicyServiceServer interface {
	mustEmbedUnimplementedClientPolicyServiceServer()
}

func RegisterClientPolicyServiceServer(s grpc.ServiceRegistrar, srv ClientPolicyServiceServer) {
	// If the following call panics, it indicates UnimplementedClientPolicyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClientPolicyService_ServiceDesc, srv)
}

func _ClientPolicyService_GetCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientPolicyServiceServer).GetCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientPolicyService_GetCapabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientPolicyServiceServer).GetCapabilities(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientPolicyService_GetClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientPolicyServiceServer).GetClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientPolicyService_GetClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientPolicyServiceServer).GetClient(ctx, req.(*ClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientPolicyService_ApplyPolicies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientPolicyServiceServer).ApplyPolicies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientPolicyService_ApplyPolicies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientPolicyServiceServer).ApplyPolicies(ctx, req.(*ApplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientPolicyService_InitializeClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitializeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientPolicyServiceServer).InitializeClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientPolicyService_InitializeClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientPolicyServiceServer).InitializeClient(ctx, req.(*InitializeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientPolicyService_RevokeClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientPolicyServiceServer).RevokeClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientPolicyService_RevokeClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientPolicyServiceServer).RevokeClient(ctx, req.(*ClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientPolicyService_ListConnections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientPolicyServiceServer).ListConnections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientPolicyService_ListConnections_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientPolicyServiceServer).ListConnections(ctx, req.(*ClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientPolicyService_CloseConnections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientPolicyServiceServer).CloseConnections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientPolicyService_CloseConnections_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientPolicyServiceServer).CloseConnections(ctx, req.(*ClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientPolicyService_CheckpointUsage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientPolicyServiceServer).CheckpointUsage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientPolicyService_CheckpointUsage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientPolicyServiceServer).CheckpointUsage(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientPolicyService_ReadLedger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LedgerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientPolicyServiceServer).ReadLedger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientPolicyService_ReadLedger_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientPolicyServiceServer).ReadLedger(ctx, req.(*LedgerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClientPolicyService_ServiceDesc is the grpc.ServiceDesc for ClientPolicyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClientPolicyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xray.app.clientpolicy.command.v1.ClientPolicyService",
	HandlerType: (*ClientPolicyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCapabilities",
			Handler:    _ClientPolicyService_GetCapabilities_Handler,
		},
		{
			MethodName: "GetClient",
			Handler:    _ClientPolicyService_GetClient_Handler,
		},
		{
			MethodName: "ApplyPolicies",
			Handler:    _ClientPolicyService_ApplyPolicies_Handler,
		},
		{
			MethodName: "InitializeClient",
			Handler:    _ClientPolicyService_InitializeClient_Handler,
		},
		{
			MethodName: "RevokeClient",
			Handler:    _ClientPolicyService_RevokeClient_Handler,
		},
		{
			MethodName: "ListConnections",
			Handler:    _ClientPolicyService_ListConnections_Handler,
		},
		{
			MethodName: "CloseConnections",
			Handler:    _ClientPolicyService_CloseConnections_Handler,
		},
		{
			MethodName: "CheckpointUsage",
			Handler:    _ClientPolicyService_CheckpointUsage_Handler,
		},
		{
			MethodName: "ReadLedger",
			Handler:    _ClientPolicyService_ReadLedger_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/clientpolicy/command/command.proto",
}
