// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: app/clientpolicy/command/command.proto

package command

import (
	clientpolicy "github.com/xtls/xray-core/app/clientpolicy"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_app_clientpolicy_command_command_proto_rawDescGZIP(), []int{0}
}

type ClientRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ClientId              string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ExpectedPolicyVersion uint64                 `protobuf:"varint,2,opt,name=expected_policy_version,json=expectedPolicyVersion,proto3" json:"expected_policy_version,omitempty"`
	InboundTag            string                 `protobuf:"bytes,3,opt,name=inbound_tag,json=inboundTag,proto3" json:"inbound_tag,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ClientRequest) Reset() {
	*x = ClientRequest{}
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientRequest) ProtoMessage() {}

func (x *ClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientRequest.ProtoReflect.Descriptor instead.
func (*ClientRequest) Descriptor() ([]byte, []int) {
	return file_app_clientpolicy_command_command_proto_rawDescGZIP(), []int{1}
}

func (x *ClientRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ClientRequest) GetExpectedPolicyVersion() uint64 {
	if x != nil {
		return x.ExpectedPolicyVersion
	}
	return 0
}

func (x *ClientRequest) GetInboundTag() string {
	if x != nil {
		return x.InboundTag
	}
	return ""
}

type Capabilities struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion          uint32                 `protobuf:"varint,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	CoreVersion         string                 `protobuf:"bytes,2,opt,name=core_version,json=coreVersion,proto3" json:"core_version,omitempty"`
	InstanceId          string                 `protobuf:"bytes,3,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Epoch               uint64                 `protobuf:"varint,4,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Capabilities        []string               `protobuf:"bytes,5,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	ReservationRawBytes uint64                 `protobuf:"varint,6,opt,name=reservation_raw_bytes,json=reservationRawBytes,proto3" json:"reservation_raw_bytes,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Capabilities) Reset() {
	*x = Capabilities{}
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capabilities) ProtoMessage() {}

func (x *Capabilities) ProtoReflect() protoreflect.Message {
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capabilities.ProtoReflect.Descriptor instead.
func (*Capabilities) Descriptor() ([]byte, []int) {
	return file_app_clientpolicy_command_command_proto_rawDescGZIP(), []int{2}
}

func (x *Capabilities) GetApiVersion() uint32 {
	if x != nil {
		return x.ApiVersion
	}
	return 0
}

func (x *Capabilities) GetCoreVersion() string {
	if x != nil {
		return x.CoreVersion
	}
	return ""
}

func (x *Capabilities) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *Capabilities) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *Capabilities) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *Capabilities) GetReservationRawBytes() uint64 {
	if x != nil {
		return x.ReservationRawBytes
	}
	return 0
}

type Usage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RawUpload     uint64                 `protobuf:"varint,1,opt,name=raw_upload,json=rawUpload,proto3" json:"raw_upload,omitempty"`
	RawDownload   uint64                 `protobuf:"varint,2,opt,name=raw_download,json=rawDownload,proto3" json:"raw_download,omitempty"`
	BilledBytes   uint64                 `protobuf:"varint,3,opt,name=billed_bytes,json=billedBytes,proto3" json:"billed_bytes,omitempty"`
	Remainder     uint64                 `protobuf:"varint,4,opt,name=remainder,proto3" json:"remainder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Usage) Reset() {
	*x = Usage{}
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Usage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Usage) ProtoMessage() {}

func (x *Usage) ProtoReflect() protoreflect.Message {
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Usage.ProtoReflect.Descriptor instead.
func (*Usage) Descriptor() ([]byte, []int) {
	return file_app_clientpolicy_command_command_proto_rawDescGZIP(), []int{3}
}

func (x *Usage) GetRawUpload() uint64 {
	if x != nil {
		return x.RawUpload
	}
	return 0
}

func (x *Usage) GetRawDownload() uint64 {
	if x != nil {
		return x.RawDownload
	}
	return 0
}

func (x *Usage) GetBilledBytes() uint64 {
	if x != nil {
		return x.BilledBytes
	}
	return 0
}

func (x *Usage) GetRemainder() uint64 {
	if x != nil {
		return x.Remainder
	}
	return 0
}

type ClientState struct {
	state          protoimpl.MessageState     `protogen:"open.v1"`
	Policy         *clientpolicy.PolicyConfig `protobuf:"bytes,1,opt,name=policy,proto3" json:"policy,omitempty"`
	Usage          *Usage                     `protobuf:"bytes,2,opt,name=usage,proto3" json:"usage,omitempty"`
	UncertainBytes uint64                     `protobuf:"varint,3,opt,name=uncertain_bytes,json=uncertainBytes,proto3" json:"uncertain_bytes,omitempty"`
	Reasons        uint32                     `protobuf:"varint,4,opt,name=reasons,proto3" json:"reasons,omitempty"`
	ActiveSessions uint32                     `protobuf:"varint,5,opt,name=active_sessions,json=activeSessions,proto3" json:"active_sessions,omitempty"`
	FirstUsedAt    int64                      `protobuf:"varint,6,opt,name=first_used_at,json=firstUsedAt,proto3" json:"first_used_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ClientState) Reset() {
	*x = ClientState{}
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientState) ProtoMessage() {}

func (x *ClientState) ProtoReflect() protoreflect.Message {
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientState.ProtoReflect.Descriptor instead.
func (*ClientState) Descriptor() ([]byte, []int) {
	return file_app_clientpolicy_command_command_proto_rawDescGZIP(), []int{4}
}

func (x *ClientState) GetPolicy() *clientpolicy.PolicyConfig {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *ClientState) GetUsage() *Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *ClientState) GetUncertainBytes() uint64 {
	if x != nil {
		return x.UncertainBytes
	}
	return 0
}

func (x *ClientState) GetReasons() uint32 {
	if x != nil {
		return x.Reasons
	}
	return 0
}

func (x *ClientState) GetActiveSessions() uint32 {
	if x != nil {
		return x.ActiveSessions
	}
	return 0
}

func (x *ClientState) GetFirstUsedAt() int64 {
	if x != nil {
		return x.FirstUsedAt
	}
	return 0
}

type ApplyRequest struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Policies      []*clientpolicy.PolicyConfig `protobuf:"bytes,1,rep,name=policies,proto3" json:"policies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyRequest) Reset() {
	*x = ApplyRequest{}
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyRequest) ProtoMessage() {}

func (x *ApplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyRequest.ProtoReflect.Descriptor instead.
func (*ApplyRequest) Descriptor() ([]byte, []int) {
	return file_app_clientpolicy_command_command_proto_rawDescGZIP(), []int{5}
}

func (x *ApplyRequest) GetPolicies() []*clientpolicy.PolicyConfig {
	if x != nil {
		return x.Policies
	}
	return nil
}

type InitializeRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Policy        *clientpolicy.PolicyConfig `protobuf:"bytes,1,opt,name=policy,proto3" json:"policy,omitempty"`
	Usage         *Usage                     `protobuf:"bytes,2,opt,name=usage,proto3" json:"usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitializeRequest) Reset() {
	*x = InitializeRequest{}
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeRequest) ProtoMessage() {}

func (x *InitializeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeRequest.ProtoReflect.Descriptor instead.
func (*InitializeRequest) Descriptor() ([]byte, []int) {
	return file_app_clientpolicy_command_command_proto_rawDescGZIP(), []int{6}
}

func (x *InitializeRequest) GetPolicy() *clientpolicy.PolicyConfig {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *InitializeRequest) GetUsage() *Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

type Connection struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	SessionId            uint64                 `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	InboundTag           string                 `protobuf:"bytes,2,opt,name=inbound_tag,json=inboundTag,proto3" json:"inbound_tag,omitempty"`
	AuthenticatedAccount string                 `protobuf:"bytes,3,opt,name=authenticated_account,json=authenticatedAccount,proto3" json:"authenticated_account,omitempty"`
	OriginalTarget       string                 `protobuf:"bytes,4,opt,name=original_target,json=originalTarget,proto3" json:"original_target,omitempty"`
	ActualTarget         string                 `protobuf:"bytes,5,opt,name=actual_target,json=actualTarget,proto3" json:"actual_target,omitempty"`
	PolicyVersion        uint64                 `protobuf:"varint,6,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Connection) Reset() {
	*x = Connection{}
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Connection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Connection) ProtoMessage() {}

func (x *Connection) ProtoReflect() protoreflect.Message {
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Connection.ProtoReflect.Descriptor instead.
func (*Connection) Descriptor() ([]byte, []int) {
	return file_app_clientpolicy_command_command_proto_rawDescGZIP(), []int{7}
}

func (x *Connection) GetSessionId() uint64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *Connection) GetInboundTag() string {
	if x != nil {
		return x.InboundTag
	}
	return ""
}

func (x *Connection) GetAuthenticatedAccount() string {
	if x != nil {
		return x.AuthenticatedAccount
	}
	return ""
}

func (x *Connection) GetOriginalTarget() string {
	if x != nil {
		return x.OriginalTarget
	}
	return ""
}

func (x *Connection) GetActualTarget() string {
	if x != nil {
		return x.ActualTarget
	}
	return ""
}

func (x *Connection) GetPolicyVersion() uint64 {
	if x != nil {
		return x.PolicyVersion
	}
	return 0
}

type Connections struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connections   []*Connection          `protobuf:"bytes,1,rep,name=connections,proto3" json:"connections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Connections) Reset() {
	*x = Connections{}
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Connections) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Connections) ProtoMessage() {}

func (x *Connections) ProtoReflect() protoreflect.Message {
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Connections.ProtoReflect.Descriptor instead.
func (*Connections) Descriptor() ([]byte, []int) {
	return file_app_clientpolicy_command_command_proto_rawDescGZIP(), []int{8}
}

func (x *Connections) GetConnections() []*Connection {
	if x != nil {
		return x.Connections
	}
	return nil
}

type CloseResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Closed        uint32                 `protobuf:"varint,1,opt,name=closed,proto3" json:"closed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseResult) Reset() {
	*x = CloseResult{}
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseResult) ProtoMessage() {}

func (x *CloseResult) ProtoReflect() protoreflect.Message {
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseResult.ProtoReflect.Descriptor instead.
func (*CloseResult) Descriptor() ([]byte, []int) {
	return file_app_clientpolicy_command_command_proto_rawDescGZIP(), []int{9}
}

func (x *CloseResult) GetClosed() uint32 {
	if x != nil {
		return x.Closed
	}
	return 0
}

type LedgerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AfterSequence uint64                 `protobuf:"varint,1,opt,name=after_sequence,json=afterSequence,proto3" json:"after_sequence,omitempty"`
	Limit         uint32                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LedgerRequest) Reset() {
	*x = LedgerRequest{}
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedgerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerRequest) ProtoMessage() {}

func (x *LedgerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedgerRequest.ProtoReflect.Descriptor instead.
func (*LedgerRequest) Descriptor() ([]byte, []int) {
	return file_app_clientpolicy_command_command_proto_rawDescGZIP(), []int{10}
}

func (x *LedgerRequest) GetAfterSequence() uint64 {
	if x != nil {
		return x.AfterSequence
	}
	return 0
}

func (x *LedgerRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type LedgerRecord struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	InstanceId     string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Epoch          uint64                 `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Sequence       uint64                 `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	ClientId       string                 `protobuf:"bytes,4,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	PolicyVersion  uint64                 `protobuf:"varint,5,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	Usage          *Usage                 `protobuf:"bytes,6,opt,name=usage,proto3" json:"usage,omitempty"`
	UncertainBytes uint64                 `protobuf:"varint,7,opt,name=uncertain_bytes,json=uncertainBytes,proto3" json:"uncertain_bytes,omitempty"`
	ReservedBytes  uint64                 `protobuf:"varint,8,opt,name=reserved_bytes,json=reservedBytes,proto3" json:"reserved_bytes,omitempty"`
	Revoked        bool                   `protobuf:"varint,9,opt,name=revoked,proto3" json:"revoked,omitempty"`
	FirstUsedAt    int64                  `protobuf:"varint,10,opt,name=first_used_at,json=firstUsedAt,proto3" json:"first_used_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LedgerRecord) Reset() {
	*x = LedgerRecord{}
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedgerRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerRecord) ProtoMessage() {}

func (x *LedgerRecord) ProtoReflect() protoreflect.Message {
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedgerRecord.ProtoReflect.Descriptor instead.
func (*LedgerRecord) Descriptor() ([]byte, []int) {
	return file_app_clientpolicy_command_command_proto_rawDescGZIP(), []int{11}
}

func (x *LedgerRecord) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *LedgerRecord) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *LedgerRecord) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *LedgerRecord) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *LedgerRecord) GetPolicyVersion() uint64 {
	if x != nil {
		return x.PolicyVersion
	}
	return 0
}

func (x *LedgerRecord) GetUsage() *Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *LedgerRecord) GetUncertainBytes() uint64 {
	if x != nil {
		return x.UncertainBytes
	}
	return 0
}

func (x *LedgerRecord) GetReservedBytes() uint64 {
	if x != nil {
		return x.ReservedBytes
	}
	return 0
}

func (x *LedgerRecord) GetRevoked() bool {
	if x != nil {
		return x.Revoked
	}
	return false
}

func (x *LedgerRecord) GetFirstUsedAt() int64 {
	if x != nil {
		return x.FirstUsedAt
	}
	return 0
}

type LedgerPage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*LedgerRecord        `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	NextSequence  uint64                 `protobuf:"varint,2,opt,name=next_sequence,json=nextSequence,proto3" json:"next_sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LedgerPage) Reset() {
	*x = LedgerPage{}
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedgerPage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerPage) ProtoMessage() {}

func (x *LedgerPage) ProtoReflect() protoreflect.Message {
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedgerPage.ProtoReflect.Descriptor instead.
func (*LedgerPage) Descriptor() ([]byte, []int) {
	return file_app_clientpolicy_command_command_proto_rawDescGZIP(), []int{12}
}

func (x *LedgerPage) GetRecords() []*LedgerRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *LedgerPage) GetNextSequence() uint64 {
	if x != nil {
		return x.NextSequence
	}
	return 0
}

type Config struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_app_clientpolicy_command_command_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_app_clientpolicy_command_command_proto_rawDescGZIP(), []int{13}
}

var File_app_clientpolicy_command_command_proto protoreflect.FileDescriptor

const file_app_clientpolicy_command_command_proto_rawDesc = "" +
	"\n" +
	"&app/clientpolicy/command/command.proto\x12 xray.app.clientpolicy.command.v1\x1a\x1dapp/clientpolicy/config.proto\"\a\n" +
	"\x05Empty\"\x85\x01\n" +
	"\rClientRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x126\n" +
	"\x17expected_policy_version\x18\x02 \x01(\x04R\x15expectedPolicyVersion\x12\x1f\n" +
	"\vinbound_tag\x18\x03 \x01(\tR\n" +
	"inboundTag\"\xe1\x01\n" +
	"\fCapabilities\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\rR\n" +
	"apiVersion\x12!\n" +
	"\fcore_version\x18\x02 \x01(\tR\vcoreVersion\x12\x1f\n" +
	"\vinstance_id\x18\x03 \x01(\tR\n" +
	"instanceId\x12\x14\n" +
	"\x05epoch\x18\x04 \x01(\x04R\x05epoch\x12\"\n" +
	"\fcapabilities\x18\x05 \x03(\tR\fcapabilities\x122\n" +
	"\x15reservation_raw_bytes\x18\x06 \x01(\x04R\x13reservationRawBytes\"\x8a\x01\n" +
	"\x05Usage\x12\x1d\n" +
	"\n" +
	"raw_upload\x18\x01 \x01(\x04R\trawUpload\x12!\n" +
	"\fraw_download\x18\x02 \x01(\x04R\vrawDownload\x12!\n" +
	"\fbilled_bytes\x18\x03 \x01(\x04R\vbilledBytes\x12\x1c\n" +
	"\tremainder\x18\x04 \x01(\x04R\tremainder\"\x99\x02\n" +
	"\vClientState\x12;\n" +
	"\x06policy\x18\x01 \x01(\v2#.xray.app.clientpolicy.PolicyConfigR\x06policy\x12=\n" +
	"\x05usage\x18\x02 \x01(\v2'.xray.app.clientpolicy.command.v1.UsageR\x05usage\x12'\n" +
	"\x0funcertain_bytes\x18\x03 \x01(\x04R\x0euncertainBytes\x12\x18\n" +
	"\areasons\x18\x04 \x01(\rR\areasons\x12'\n" +
	"\x0factive_sessions\x18\x05 \x01(\rR\x0eactiveSessions\x12\"\n" +
	"\rfirst_used_at\x18\x06 \x01(\x03R\vfirstUsedAt\"O\n" +
	"\fApplyRequest\x12?\n" +
	"\bpolicies\x18\x01 \x03(\v2#.xray.app.clientpolicy.PolicyConfigR\bpolicies\"\x8f\x01\n" +
	"\x11InitializeRequest\x12;\n" +
	"\x06policy\x18\x01 \x01(\v2#.xray.app.clientpolicy.PolicyConfigR\x06policy\x12=\n" +
	"\x05usage\x18\x02 \x01(\v2'.xray.app.clientpolicy.command.v1.UsageR\x05usage\"\xf6\x01\n" +
	"\n" +
	"Connection\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\x04R\tsessionId\x12\x1f\n" +
	"\vinbound_tag\x18\x02 \x01(\tR\n" +
	"inboundTag\x123\n" +
	"\x15authenticated_account\x18\x03 \x01(\tR\x14authenticatedAccount\x12'\n" +
	"\x0foriginal_target\x18\x04 \x01(\tR\x0eoriginalTarget\x12#\n" +
	"\ractual_target\x18\x05 \x01(\tR\factualTarget\x12%\n" +
	"\x0epolicy_version\x18\x06 \x01(\x04R\rpolicyVersion\"]\n" +
	"\vConnections\x12N\n" +
	"\vconnections\x18\x01 \x03(\v2,.xray.app.clientpolicy.command.v1.ConnectionR\vconnections\"%\n" +
	"\vCloseResult\x12\x16\n" +
	"\x06closed\x18\x01 \x01(\rR\x06closed\"L\n" +
	"\rLedgerRequest\x12%\n" +
	"\x0eafter_sequence\x18\x01 \x01(\x04R\rafterSequence\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\"\xf2\x02\n" +
	"\fLedgerRecord\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\x04R\x05epoch\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x04R\bsequence\x12\x1b\n" +
	"\tclient_id\x18\x04 \x01(\tR\bclientId\x12%\n" +
	"\x0epolicy_version\x18\x05 \x01(\x04R\rpolicyVersion\x12=\n" +
	"\x05usage\x18\x06 \x01(\v2'.xray.app.clientpolicy.command.v1.UsageR\x05usage\x12'\n" +
	"\x0funcertain_bytes\x18\a \x01(\x04R\x0euncertainBytes\x12%\n" +
	"\x0ereserved_bytes\x18\b \x01(\x04R\rreservedBytes\x12\x18\n" +
	"\arevoked\x18\t \x01(\bR\arevoked\x12\"\n" +
	"\rfirst_used_at\x18\n" +
	" \x01(\x03R\vfirstUsedAt\"{\n" +
	"\n" +
	"LedgerPage\x12H\n" +
	"\arecords\x18\x01 \x03(\v2..xray.app.clientpolicy.command.v1.LedgerRecordR\arecords\x12#\n" +
	"\rnext_sequence\x18\x02 \x01(\x04R\fnextSequence\"\b\n" +
	"\x06Config2\xed\a\n" +
	"\x13ClientPolicyService\x12j\n" +
	"\x0fGetCapabilities\x12'.xray.app.clientpolicy.command.v1.Empty\x1a..xray.app.clientpolicy.command.v1.Capabilities\x12k\n" +
	"\tGetClient\x12/.xray.app.clientpolicy.command.v1.ClientRequest\x1a-.xray.app.clientpolicy.command.v1.ClientState\x12h\n" +
	"\rApplyPolicies\x12..xray.app.clientpolicy.command.v1.ApplyRequest\x1a'.xray.app.clientpolicy.command.v1.Empty\x12p\n" +
	"\x10InitializeClient\x123.xray.app.clientpolicy.command.v1.InitializeRequest\x1a'.xray.app.clientpolicy.command.v1.Empty\x12h\n" +
	"\fRevokeClient\x12/.xray.app.clientpolicy.command.v1.ClientRequest\x1a'.xray.app.clientpolicy.command.v1.Empty\x12q\n" +
	"\x0fListConnections\x12/.xray.app.clientpolicy.command.v1.ClientRequest\x1a-.xray.app.clientpolicy.command.v1.Connections\x12r\n" +
	"\x10CloseConnections\x12/.xray.app.clientpolicy.command.v1.ClientRequest\x1a-.xray.app.clientpolicy.command.v1.CloseResult\x12c\n" +
	"\x0fCheckpointUsage\x12'.xray.app.clientpolicy.command.v1.Empty\x1a'.xray.app.clientpolicy.command.v1.Empty\x12k\n" +
	"\n" +
	"ReadLedger\x12/.xray.app.clientpolicy.command.v1.LedgerRequest\x1a,.xray.app.clientpolicy.command.v1.LedgerPageB4Z2github.com/xtls/xray-core/app/clientpolicy/commandb\x06proto3"

var (
	file_app_clientpolicy_command_command_proto_rawDescOnce sync.Once
	file_app_clientpolicy_command_command_proto_rawDescData []byte
)

func file_app_clientpolicy_command_command_proto_rawDescGZIP() []byte {
	file_app_clientpolicy_command_command_proto_rawDescOnce.Do(func() {
		file_app_clientpolicy_command_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_clientpolicy_command_command_proto_rawDesc), len(file_app_clientpolicy_command_command_proto_rawDesc)))
	})
	return file_app_clientpolicy_command_command_proto_rawDescData
}

var file_app_clientpolicy_command_command_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_app_clientpolicy_command_command_proto_goTypes = []any{
	(*Empty)(nil),                     // 0: xray.app.clientpolicy.command.v1.Empty
	(*ClientRequest)(nil),             // 1: xray.app.clientpolicy.command.v1.ClientRequest
	(*Capabilities)(nil),              // 2: xray.app.clientpolicy.command.v1.Capabilities
	(*Usage)(nil),                     // 3: xray.app.clientpolicy.command.v1.Usage
	(*ClientState)(nil),               // 4: xray.app.clientpolicy.command.v1.ClientState
	(*ApplyRequest)(nil),              // 5: xray.app.clientpolicy.command.v1.ApplyRequest
	(*InitializeRequest)(nil),         // 6: xray.app.clientpolicy.command.v1.InitializeRequest
	(*Connection)(nil),                // 7: xray.app.clientpolicy.command.v1.Connection
	(*Connections)(nil),               // 8: xray.app.clientpolicy.command.v1.Connections
	(*CloseResult)(nil),               // 9: xray.app.clientpolicy.command.v1.CloseResult
	(*LedgerRequest)(nil),             // 10: xray.app.clientpolicy.command.v1.LedgerRequest
	(*LedgerRecord)(nil),              // 11: xray.app.clientpolicy.command.v1.LedgerRecord
	(*LedgerPage)(nil),                // 12: xray.app.clientpolicy.command.v1.LedgerPage
	(*Config)(nil),                    // 13: xray.app.clientpolicy.command.v1.Config
	(*clientpolicy.PolicyConfig)(nil), // 14: xray.app.clientpolicy.PolicyConfig
}
var file_app_clientpolicy_command_command_proto_depIdxs = []int32{
	14, // 0: xray.app.clientpolicy.command.v1.ClientState.policy:type_name -> xray.app.clientpolicy.PolicyConfig
	3,  // 1: xray.app.clientpolicy.command.v1.ClientState.usage:type_name -> xray.app.clientpolicy.command.v1.Usage
	14, // 2: xray.app.clientpolicy.command.v1.ApplyRequest.policies:type_name -> xray.app.clientpolicy.PolicyConfig
	14, // 3: xray.app.clientpolicy.command.v1.InitializeRequest.policy:type_name -> xray.app.clientpolicy.PolicyConfig
	3,  // 4: xray.app.clientpolicy.command.v1.InitializeRequest.usage:type_name -> xray.app.clientpolicy.command.v1.Usage
	7,  // 5: xray.app.clientpolicy.command.v1.Connections.connections:type_name -> xray.app.clientpolicy.command.v1.Connection
	3,  // 6: xray.app.clientpolicy.command.v1.LedgerRecord.usage:type_name -> xray.app.clientpolicy.command.v1.Usage
	11, // 7: xray.app.clientpolicy.command.v1.LedgerPage.records:type_name -> xray.app.clientpolicy.command.v1.LedgerRecord
	0,  // 8: xray.app.clientpolicy.command.v1.ClientPolicyService.GetCapabilities:input_type -> xray.app.clientpolicy.command.v1.Empty
	1,  // 9: xray.app.clientpolicy.command.v1.ClientPolicyService.GetClient:input_type -> xray.app.clientpolicy.command.v1.ClientRequest
	5,  // 10: xray.app.clientpolicy.command.v1.ClientPolicyService.ApplyPolicies:input_type -> xray.app.clientpolicy.command.v1.ApplyRequest
	6,  // 11: xray.app.clientpolicy.command.v1.ClientPolicyService.InitializeClient:input_type -> xray.app.clientpolicy.command.v1.InitializeRequest
	1,  // 12: xray.app.clientpolicy.command.v1.ClientPolicyService.RevokeClient:input_type -> xray.app.clientpolicy.command.v1.ClientRequest
	1,  // 13: xray.app.clientpolicy.command.v1.ClientPolicyService.ListConnections:input_type -> xray.app.clientpolicy.command.v1.ClientRequest
	1,  // 14: xray.app.clientpolicy.command.v1.ClientPolicyService.CloseConnections:input_type -> xray.app.clientpolicy.command.v1.ClientRequest
	0,  // 15: xray.app.clientpolicy.command.v1.ClientPolicyService.CheckpointUsage:input_type -> xray.app.clientpolicy.command.v1.Empty
	10, // 16: xray.app.clientpolicy.command.v1.ClientPolicyService.ReadLedger:input_type -> xray.app.clientpolicy.command.v1.LedgerRequest
	2,  // 17: xray.app.clientpolicy.command.v1.ClientPolicyService.GetCapabilities:output_type -> xray.app.clientpolicy.command.v1.Capabilities
	4,  // 18: xray.app.clientpolicy.command.v1.ClientPolicyService.GetClient:output_type -> xray.app.clientpolicy.command.v1.ClientState
	0,  // 19: xray.app.clientpolicy.command.v1.ClientPolicyService.ApplyPolicies:output_type -> xray.app.clientpolicy.command.v1.Empty
	0,  // 20: xray.app.clientpolicy.command.v1.ClientPolicyService.InitializeClient:output_type -> xray.app.clientpolicy.command.v1.Empty
	0,  // 21: xray.app.clientpolicy.command.v1.ClientPolicyService.RevokeClient:output_type -> xray.app.clientpolicy.command.v1.Empty
	8,  // 22: xray.app.clientpolicy.command.v1.ClientPolicyService.ListConnections:output_type -> xray.app.clientpolicy.command.v1.Connections
	9,  // 23: xray.app.clientpolicy.command.v1.ClientPolicyService.CloseConnections:output_type -> xray.app.clientpolicy.command.v1.CloseResult
	0,  // 24: xray.app.clientpolicy.command.v1.ClientPolicyService.CheckpointUsage:output_type -> xray.app.clientpolicy.command.v1.Empty
	12, // 25: xray.app.clientpolicy.command.v1.ClientPolicyService.ReadLedger:output_type -> xray.app.clientpolicy.command.v1.LedgerPage
	17, // [17:26] is the sub-list for method output_type
	8,  // [8:17] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_app_clientpolicy_command_command_proto_init() }
func file_app_clientpolicy_command_command_proto_init() {
	if File_app_clientpolicy_command_command_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_clientpolicy_command_command_proto_rawDesc), len(file_app_clientpolicy_command_command_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_clientpolicy_command_command_proto_goTypes,
		DependencyIndexes: file_app_clientpolicy_command_command_proto_depIdxs,
		MessageInfos:      file_app_clientpolicy_command_command_proto_msgTypes,
	}.Build()
	File_app_clientpolicy_command_command_proto = out.File
	file_app_clientpolicy_command_command_proto_goTypes = nil
	file_app_clientpolicy_command_command_proto_depIdxs = nil
}
